## CSV file database

functions we need: 

1. add strains or dna to a specific sheet
    - update_id(): A Function to automatically give the next UNIQUE ID starting from 10000
    - add_to_database()
    
    
2. pull strains from a sheet - Get DNA
3. update a row or rows in a sheet 
4. Get location
4.

In [2]:
### making a csv local database 
import pandas as pd
from Bio import SeqIO
from Bio.SeqRecord import SeqRecord
from Bio.Seq import Seq

## initializing

In [2]:
list_of_well_numbers = []

for i in range(1,10): 
    i = str(i)
    if len(i) == 1: 
        i = '0'+i
    list_of_well_numbers.append(i)

list_of_well_numbers = list_of_well_numbers *9
print(len(list_of_well_numbers))

list_of_well_numbers = list_of_well_numbers *10
print(len(list_of_well_numbers))

81
810

In [3]:
list_of_boxes = []
wells = '0123456789'

for well in wells:
    listen = str(well)*81
    
    list_of_boxes+= listen
    
len(list_of_boxes)

810

In [4]:
list_of_well_names = []
wells = 'ABCDEFGHI'

for well in wells:
    listen = (well)*9
    list_of_well_names += listen

list_of_well_names = list_of_well_names*10
len(list_of_well_names)

810

In [5]:
strains = pd.DataFrame(list(zip(list_of_boxes, list_of_well_names, list_of_well_numbers)),
              columns=['plate','row', 'col'])
columns = ['ID', 'description','parts', 'parent', 'media', 'sequence', 'stock']

for names in columns: 
    strains[names] = ''
strains['ID'] = ''
strains['Description'] = ''

strains

    plate row col ID description parts parent media sequence stock Description
0       0   A  01
1       0   A  02
2       0   A  03
3       0   A  04
4       0   A  05
..    ...  ..  .. ..         ...   ...    ...   ...      ...   ...         ...
805     9   I  05
806     9   I  06
807     9   I  07
808     9   I  08
809     9   I  09

[810 rows x 11 columns]

In [6]:
## Freezer boxes
boxes = strains 

boxes = boxes.rename(columns={"plate": "box"})
boxes['date'] = ''
boxes['comments'] = ''
boxes['name'] = ''
boxes['size'] = ''
boxes['seq'] = ''
boxes['concentration'] = ''
boxes['features'] = ''
boxes['location'] = ''
boxes['reference'] = ''




boxes = boxes[['ID', 'name','box', 'row','col',  'size', 'seq', 'concentration', 'features', 'location', 'reference', 'stock', 'comments']]
boxes.to_csv('../data/csv_database/box_MASTER.csv', index = False)

# Importing boiler csv database 10 plates or boxes per database

There are two formats: 
1. Plates
2. Freezer boxes (not made yet)

In [7]:
strains = pd.read_excel('/Users/lucaslevassor/Downloads/inventory.xlsx', sheet_name = 'strains')
e_coli_strains = pd.read_excel('/Users/lucaslevassor/Downloads/inventory.xlsx', sheet_name = 'eStrains')
plasmids = pd.read_excel('/Users/lucaslevassor/Downloads/inventory.xlsx', sheet_name = 'plasmids')
ds_DNA_plate = pd.read_excel('/Users/lucaslevassor/Downloads/inventory.xlsx', sheet_name = 'ds_dna')

In [8]:
strains_df = strains.iloc[0:0]
strains_df=strains_df.rename(columns = {'sdp_id':'ID'})

strains_df

Empty DataFrame
Columns: [ID, date, hour, plate, row, col, description, parts, parent, media,  , seq, features, location, reference, stock]
Index: []

In [9]:
ds_DNA_plate['concentration'] = ''
ds_DNA_plate

Empty DataFrame
Columns: [ID, date, hour, plate, row, col, description, temp_name, fw_name, rv_name, size, seq, features, location, reference, stock, Comments, concentration]
Index: []

In [10]:
from Bio import SeqIO
CPR_templates = []
G8H_templates = []

# GEtting the objects from the gb files
for seq_record in SeqIO.parse('../data/G8H_CPR_parts/CPR_tCYC1_-_2022-06-06.gb', format= 'gb'):
    CPR_templates.append(seq_record)
    
# GEtting the objects from the fasta files
for seq_record in SeqIO.parse('../data/G8H_CPR_parts/G8H_tADH1_-_2022-06-23.gb', format= 'gb'):
    G8H_templates.append(seq_record)

In [11]:
for annotations in CPR_templates: 
    annotations.annotations = {'concentration': 100, 'reference':'','stock':'', 'comments':'' ,'temp_name':'' , 'fw_name':'', 'rv_name':''}

In [12]:
CPR_templates[0].annotations

{'concentration': 100,
 'reference': '',
 'stock': '',
 'comments': '',
 'temp_name': '',
 'fw_name': '',
 'rv_name': ''}

In [13]:
len(list_of_boxes), len(list_of_well_names), len(list_of_well_numbers)

(810, 810, 810)

## importing local database

In [14]:
ds_DNA_plates = pd.read_csv('../data/csv_database/plate_MASTER.csv', index_col=False)
#ds_DNA_plates['date'] = ''

#ds_DNA_plates = ds_DNA_plates[['ID','name','date','plate','row','col','size','seq','concentration','features','location','reference','stock','comments']]
ds_DNA_plates.to_csv('../data/csv_database/ds_dna_plates.csv', index=False)

In [15]:
ds_DNA_plates

,ID,name,date,plate,row,col,size,seq,concentration,features,location,reference,stock,comments
0,NaN,NaN,NaN,0,A,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,0,A,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,0,A,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,0,A,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,0,A,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
955,NaN,NaN,NaN,9,H,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
956,NaN,NaN,NaN,9,H,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
957,NaN,NaN,NaN,9,H,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
958,NaN,NaN,NaN,9,H,11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
959,NaN,NaN,NaN,9,H,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
import os
import numpy as np
def get_unique_id(path = '../data/csv_database')-> int: 
    # get list of files
    files = os.listdir(path)

    # get csv files - sometimes there is a jupyter file or something here
    csv_files =[]
    for csv in files: 
        if csv.endswith('csv'): 
            csv_files.append(csv)
    # Pandas dataframe
    dataframes = []
    list_of_ids = []
    for df in csv_files:
        dataframe = pd.read_csv(path+'/'+df)
        list_of_ids += dataframe['ID'].to_list()
    
    
    # making an array of the and removing nan 
    arr = np.array(list_of_ids)
    new_data = arr[~np.isnan(arr)]

    # If it is the first ID
    if new_data.size == 0: 
        return 10000
    else: 
        return int(np.amax(new_data))+1

get_unique_id()

10000

In [5]:
get_unique_id()

10000

In [6]:
def add_sequences_to_dataframe(list_of_DNA:list,csv_database_as_df, index = 0 )->None: 
    '''Adds sequences to local csv databse.
    
    Parameters
    ----------
    list_of_DNA : list
        BioSeqrecord objects
        
    csv_database_as_df : pd.DataFrame
        your temporary csv database made into a pandas dataframe
        
    index : int
        designating which index you want the dna i.e could choose index= 288 which is plate 3 A1
        
    Returns
    -------
    None
        updates the dateframe with your sequences
    
    
    '''
    counter = 0
    for ds_dna in list_of_DNA:
        # find index x
        if index != 0: 
            blank_row_index = index+counter
            counter += 1
        else: 
        #Find blank id spot
            blank_row_bool = csv_database_as_df.loc[:,'ID'].isna()                             # get NaN records
            blank_row_index =  [i+index for i, x in enumerate(blank_row_bool) if x][0] # get first index with nan ID

        # Changing the dataframe
        csv_database_as_df.loc[blank_row_index,'ID'] = int(ds_dna.id)
        csv_database_as_df.loc[blank_row_index, 'description'] = ds_dna.description
        csv_database_as_df.loc[blank_row_index, 'size'] = len(ds_dna.seq)
        csv_database_as_df.loc[blank_row_index, 'seq'] = str(ds_dna.seq)
        csv_database_as_df.loc[blank_row_index,'date'] = str(pd.to_datetime('today').strftime("%m-%d-%Y"))
        csv_database_as_df.loc[blank_row_index, 'name'] = ds_dna.name
        csv_database_as_df.loc[blank_row_index,'features'] = str(ds_dna.features)

        # annotations
        #csv_database_as_df.loc[blank_row_index,'temp_name'] = ds_dna.annotations['temp_name']
        #csv_database_as_df.loc[blank_row_index,'fw_name'] = ds_dna.annotations['fw_name']
        #csv_database_as_df.loc[blank_row_index,'rv_name'] = ds_dna.annotations['rv_name']
        csv_database_as_df.loc[blank_row_index,'concentration'] = ds_dna.annotations['concentration']
        csv_database_as_df.loc[blank_row_index,'comments'] = ds_dna.annotations['comments']
        csv_database_as_df.loc[blank_row_index,'reference'] = ds_dna.annotations['reference']
        csv_database_as_df.loc[blank_row_index,'stock'] = ds_dna.annotations['stock']

In [7]:
def get_plate(plate_number:int, csv_database_as_df): 
    
    ''' Returns the plate from a specified csv_database. 
    Parameters
    ----------
    plate_number : int
        designating which plate to fetch
    csv_database_as_df : pd.DataFrame
        your temporary csv database made into a pandas dataframe
        
    Returns
    -------
    pd.Dataframe
        dataframe with the specified plate
        
    '''    
    plate = csv_database_as_df.loc[csv_database_as_df['plate']==plate_number]
    
    return plate


def get_box(plate_number:int, csv_database_as_df): 
    
    ''' Returns the plate from a specified csv_database. 
    Parameters
    ----------
    plate_number : int
        designating which plate to fetch
    csv_database_as_df : pd.DataFrame
        your temporary csv database made into a pandas dataframe
        
    Returns
    -------
    pd.Dataframe
        dataframe with the specified plate
        
    '''    
    plate = csv_database_as_df.loc[csv_database_as_df['box']==plate_number]
    
    return plate

In [20]:
get_plate(0, ds_DNA_plates)

,ID,name,date,plate,row,col,size,seq,concentration,features,location,reference,stock,comments
0,NaN,NaN,NaN,0,A,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,0,A,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,0,A,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,0,A,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,0,A,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91,NaN,NaN,NaN,0,H,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
92,NaN,NaN,NaN,0,H,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
93,NaN,NaN,NaN,0,H,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
94,NaN,NaN,NaN,0,H,11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
95,NaN,NaN,NaN,0,H,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [21]:
#ds_DNA.to_csv('../data/csv_database/ds_dna.csv')

In [22]:
G8H_templates

[SeqRecord(seq=Seq('GAGCGACCTCATGCTATACCTGAGAAAGCAACCTGACCTACAGGAAAGAGTTAC...CAT'), id='CcalG8H_tADH1', name='CcalG8H_tADH1', description='', dbxrefs=[]),
 SeqRecord(seq=Seq('GAGCGACCTCATGCTATACCTGAGAAAGCAACCTGACCTACAGGAAAGAGTTAC...CAT'), id='pL_01_F5\\(pRS416U-mKate2-ccdB)', name='PcoG8H_tADH1', description='', dbxrefs=[]),
 SeqRecord(seq=Seq('GAGCGACCTCATGCTATACCTGAGAAAGCAACCTGACCTACAGGAAAGAGTTAC...CAT'), id='pL_01_C5\\(pRS413-USER).0', name='CroG8H_tADH1', description='', dbxrefs=[]),
 SeqRecord(seq=Seq('GAGCGACCTCATGCTATACCTGAGAAAGCAACCTGACCTACAGGAAAGAGTTAC...CAT'), id='OpumG8H_tADH1', name='OpumG8H_tADH1', description='', dbxrefs=[]),
 SeqRecord(seq=Seq('GAGCGACCTCATGCTATACCTGAGAAAGCAACCTGACCTACAGGAAAGAGTTAC...CAT'), id='CacuG8H_tADH1', name='CacuG8H_tADH1', description='', dbxrefs=[]),
 SeqRecord(seq=Seq('GAGCGACCTCATGCTATACCTGAGAAAGCAACCTGACCTACAGGAAAGAGTTAC...CAT'), id='RsepG8H_tADH1', name='RsepG8H_tADH1', description='', dbxrefs=[]),
 SeqRecord(seq=Seq('GAGCGACCTCATGCTATACCTGAGAAAGCAACCTGACCTACAGGAAAGAGTTAC...CAT'), id='SmusG8H_tADH1', name='SmusG8H_tADH1', description='', dbxrefs=[]),
 SeqRecord(seq=Seq('GAGCGACCTCATGCTATACCTGAGAAAGCAACCTGACCTACAGGAAAGAGTTAC...CAT'), id='VminG8H_tADH1', name='VminG8H_tADH1', description='', dbxrefs=[]),
 SeqRecord(seq=Seq('GAGCGACCTCATGCTATACCTGAGAAAGCAACCTGACCTACAGGAAAGAGTTAC...CAT'), id='OeuG8H_tADH1', name='OeuG8H_tADH1', description='', dbxrefs=[])]

In [8]:
def add_unique_ids(list_of_parts:list) -> None: 
    ''' Adds unique ids to a list of SeqRecords.'''
    for i in range(len(list_of_parts)):
        unique_id = get_unique_id()+i
        list_of_parts[i].id = unique_id

In [9]:
def add_annotations(list_of_parts:list) -> None: 
    ''' Adds the neccessary annotations to SeqRecord object
    to be uploaded to the database'''
    for annotations in list_of_parts: 
        annotations.annotations = {'concentration': '', 'reference':'',
                                   'stock':'', 'comments':'' ,'temp_name':'' 
                                   , 'fw_name':'', 'rv_name':''}

In [25]:
add_unique_ids(G8H_templates)
G8H_templates

[SeqRecord(seq=Seq('GAGCGACCTCATGCTATACCTGAGAAAGCAACCTGACCTACAGGAAAGAGTTAC...CAT'), id=10000, name='CcalG8H_tADH1', description='', dbxrefs=[]),
 SeqRecord(seq=Seq('GAGCGACCTCATGCTATACCTGAGAAAGCAACCTGACCTACAGGAAAGAGTTAC...CAT'), id=10001, name='PcoG8H_tADH1', description='', dbxrefs=[]),
 SeqRecord(seq=Seq('GAGCGACCTCATGCTATACCTGAGAAAGCAACCTGACCTACAGGAAAGAGTTAC...CAT'), id=10002, name='CroG8H_tADH1', description='', dbxrefs=[]),
 SeqRecord(seq=Seq('GAGCGACCTCATGCTATACCTGAGAAAGCAACCTGACCTACAGGAAAGAGTTAC...CAT'), id=10003, name='OpumG8H_tADH1', description='', dbxrefs=[]),
 SeqRecord(seq=Seq('GAGCGACCTCATGCTATACCTGAGAAAGCAACCTGACCTACAGGAAAGAGTTAC...CAT'), id=10004, name='CacuG8H_tADH1', description='', dbxrefs=[]),
 SeqRecord(seq=Seq('GAGCGACCTCATGCTATACCTGAGAAAGCAACCTGACCTACAGGAAAGAGTTAC...CAT'), id=10005, name='RsepG8H_tADH1', description='', dbxrefs=[]),
 SeqRecord(seq=Seq('GAGCGACCTCATGCTATACCTGAGAAAGCAACCTGACCTACAGGAAAGAGTTAC...CAT'), id=10006, name='SmusG8H_tADH1', description='', dbxrefs=[]),
 SeqRecord(seq=Seq('GAGCGACCTCATGCTATACCTGAGAAAGCAACCTGACCTACAGGAAAGAGTTAC...CAT'), id=10007, name='VminG8H_tADH1', description='', dbxrefs=[]),
 SeqRecord(seq=Seq('GAGCGACCTCATGCTATACCTGAGAAAGCAACCTGACCTACAGGAAAGAGTTAC...CAT'), id=10008, name='OeuG8H_tADH1', description='', dbxrefs=[])]

In [26]:
add_annotations(G8H_templates)

In [27]:
add_sequences_to_dataframe(G8H_templates, ds_DNA_plates, index = 0)

In [28]:
#pd.set_option('display.max_rows', None)

In [29]:
new_df = get_plate(0, ds_DNA_plates)
new_df.head(20)

,ID,name,date,plate,row,col,size,seq,concentration,features,location,reference,stock,comments,description
0,10000.0,CcalG8H_tADH1,08-12-2022,0,A,1,1803.0,GAGCGACCTCATGCTATACCTGAGAAAGCAACCTGACCTACAGGAA...,,"[SeqFeature(FeatureLocation(ExactPosition(0), ...",NaN,,,,
1,10001.0,PcoG8H_tADH1,08-12-2022,0,A,2,1370.0,GAGCGACCTCATGCTATACCTGAGAAAGCAACCTGACCTACAGGAA...,,"[SeqFeature(FeatureLocation(ExactPosition(0), ...",NaN,,,,
2,10002.0,CroG8H_tADH1,08-12-2022,0,A,3,1695.0,GAGCGACCTCATGCTATACCTGAGAAAGCAACCTGACCTACAGGAA...,,"[SeqFeature(FeatureLocation(ExactPosition(0), ...",NaN,,,,
3,10003.0,OpumG8H_tADH1,08-12-2022,0,A,4,1860.0,GAGCGACCTCATGCTATACCTGAGAAAGCAACCTGACCTACAGGAA...,,"[SeqFeature(FeatureLocation(ExactPosition(0), ...",NaN,,,,
4,10004.0,CacuG8H_tADH1,08-12-2022,0,A,5,1827.0,GAGCGACCTCATGCTATACCTGAGAAAGCAACCTGACCTACAGGAA...,,"[SeqFeature(FeatureLocation(ExactPosition(0), ...",NaN,,,,
5,10005.0,RsepG8H_tADH1,08-12-2022,0,A,6,1803.0,GAGCGACCTCATGCTATACCTGAGAAAGCAACCTGACCTACAGGAA...,,"[SeqFeature(FeatureLocation(ExactPosition(0), ...",NaN,,,,
6,10006.0,SmusG8H_tADH1,08-12-2022,0,A,7,1809.0,GAGCGACCTCATGCTATACCTGAGAAAGCAACCTGACCTACAGGAA...,,"[SeqFeature(FeatureLocation(ExactPosition(0), ...",NaN,,,,
7,10007.0,VminG8H_tADH1,08-12-2022,0,A,8,1803.0,GAGCGACCTCATGCTATACCTGAGAAAGCAACCTGACCTACAGGAA...,,"[SeqFeature(FeatureLocation(ExactPosition(0), ...",NaN,,,,
8,10008.0,OeuG8H_tADH1,08-12-2022,0,A,9,1803.0,GAGCGACCTCATGCTATACCTGAGAAAGCAACCTGACCTACAGGAA...,,"[SeqFeature(FeatureLocation(ExactPosition(0), ...",NaN,,,,
9,NaN,NaN,NaN,0,A,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,0,A,11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,NaN,0,A,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,NaN,NaN,0,B,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,NaN,NaN,0,B,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,NaN,NaN,0,B,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,NaN,NaN,0,B,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,NaN,NaN,0,B,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,NaN,NaN,0,B,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,NaN,NaN,NaN,0,B,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,NaN,NaN,0,B,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
def update_database(dataframe, which_database:str, path = '../data/csv_database/') -> None:
    '''Updates the database of choosing'''
    dataframe.to_csv(path+which_database+'.csv', index=False,)

In [31]:
ds_DNA_plates.head(20)

,ID,name,date,plate,row,col,size,seq,concentration,features,location,reference,stock,comments,description
0,10000.0,CcalG8H_tADH1,08-12-2022,0,A,1,1803.0,GAGCGACCTCATGCTATACCTGAGAAAGCAACCTGACCTACAGGAA...,,"[SeqFeature(FeatureLocation(ExactPosition(0), ...",NaN,,,,
1,10001.0,PcoG8H_tADH1,08-12-2022,0,A,2,1370.0,GAGCGACCTCATGCTATACCTGAGAAAGCAACCTGACCTACAGGAA...,,"[SeqFeature(FeatureLocation(ExactPosition(0), ...",NaN,,,,
2,10002.0,CroG8H_tADH1,08-12-2022,0,A,3,1695.0,GAGCGACCTCATGCTATACCTGAGAAAGCAACCTGACCTACAGGAA...,,"[SeqFeature(FeatureLocation(ExactPosition(0), ...",NaN,,,,
3,10003.0,OpumG8H_tADH1,08-12-2022,0,A,4,1860.0,GAGCGACCTCATGCTATACCTGAGAAAGCAACCTGACCTACAGGAA...,,"[SeqFeature(FeatureLocation(ExactPosition(0), ...",NaN,,,,
4,10004.0,CacuG8H_tADH1,08-12-2022,0,A,5,1827.0,GAGCGACCTCATGCTATACCTGAGAAAGCAACCTGACCTACAGGAA...,,"[SeqFeature(FeatureLocation(ExactPosition(0), ...",NaN,,,,
5,10005.0,RsepG8H_tADH1,08-12-2022,0,A,6,1803.0,GAGCGACCTCATGCTATACCTGAGAAAGCAACCTGACCTACAGGAA...,,"[SeqFeature(FeatureLocation(ExactPosition(0), ...",NaN,,,,
6,10006.0,SmusG8H_tADH1,08-12-2022,0,A,7,1809.0,GAGCGACCTCATGCTATACCTGAGAAAGCAACCTGACCTACAGGAA...,,"[SeqFeature(FeatureLocation(ExactPosition(0), ...",NaN,,,,
7,10007.0,VminG8H_tADH1,08-12-2022,0,A,8,1803.0,GAGCGACCTCATGCTATACCTGAGAAAGCAACCTGACCTACAGGAA...,,"[SeqFeature(FeatureLocation(ExactPosition(0), ...",NaN,,,,
8,10008.0,OeuG8H_tADH1,08-12-2022,0,A,9,1803.0,GAGCGACCTCATGCTATACCTGAGAAAGCAACCTGACCTACAGGAA...,,"[SeqFeature(FeatureLocation(ExactPosition(0), ...",NaN,,,,
9,NaN,NaN,NaN,0,A,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,0,A,11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,NaN,0,A,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,NaN,NaN,0,B,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,NaN,NaN,0,B,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,NaN,NaN,0,B,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,NaN,NaN,0,B,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,NaN,NaN,0,B,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,NaN,NaN,0,B,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,NaN,NaN,NaN,0,B,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,NaN,NaN,0,B,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [32]:
update_database(ds_DNA_plates, 'ds_dna_plates')

In [133]:
def get_ds_dna(name:str, database_name:str)-> SeqRecord:
    
    # initialize
    path = '../data/csv_database/'+database_name+'.csv'
    dataframe = pd.read_csv(path)
    
    #find index of occurences of name in the dataframe and reset index
    found_the_record_df = dataframe.loc[dataframe['name']==name].reset_index()#.index[0]
    
    # Taking data from the df
    Record = SeqRecord(Seq(str(found_the_record_df.loc[0,'seq'])))
    Record.id = int(found_the_record_df.loc[0,'ID'])
    Record.name = found_the_record_df.loc[0,'name']
    Record.description = found_the_record_df.loc[0,'description']
    Record.annotations = {'plate':found_the_record_df.loc[0,'plate'],'row':found_the_record_df.loc[0,'row'],'col':found_the_record_df.loc[0,'col'], }

    return Record

In [34]:
cacug8h = get_ds_dna('CroG8H_tADH1', 'ds_dna_plates')
cacug8h

SeqRecord(seq=Seq('GAGCGACCTCATGCTATACCTGAGAAAGCAACCTGACCTACAGGAAAGAGTTAC...CAT'), id=10002, name='CroG8H_tADH1', description=nan, dbxrefs=[])

In [35]:
G8H_templates

[SeqRecord(seq=Seq('GAGCGACCTCATGCTATACCTGAGAAAGCAACCTGACCTACAGGAAAGAGTTAC...CAT'), id=10000, name='CcalG8H_tADH1', description='', dbxrefs=[]),
 SeqRecord(seq=Seq('GAGCGACCTCATGCTATACCTGAGAAAGCAACCTGACCTACAGGAAAGAGTTAC...CAT'), id=10001, name='PcoG8H_tADH1', description='', dbxrefs=[]),
 SeqRecord(seq=Seq('GAGCGACCTCATGCTATACCTGAGAAAGCAACCTGACCTACAGGAAAGAGTTAC...CAT'), id=10002, name='CroG8H_tADH1', description='', dbxrefs=[]),
 SeqRecord(seq=Seq('GAGCGACCTCATGCTATACCTGAGAAAGCAACCTGACCTACAGGAAAGAGTTAC...CAT'), id=10003, name='OpumG8H_tADH1', description='', dbxrefs=[]),
 SeqRecord(seq=Seq('GAGCGACCTCATGCTATACCTGAGAAAGCAACCTGACCTACAGGAAAGAGTTAC...CAT'), id=10004, name='CacuG8H_tADH1', description='', dbxrefs=[]),
 SeqRecord(seq=Seq('GAGCGACCTCATGCTATACCTGAGAAAGCAACCTGACCTACAGGAAAGAGTTAC...CAT'), id=10005, name='RsepG8H_tADH1', description='', dbxrefs=[]),
 SeqRecord(seq=Seq('GAGCGACCTCATGCTATACCTGAGAAAGCAACCTGACCTACAGGAAAGAGTTAC...CAT'), id=10006, name='SmusG8H_tADH1', description='', dbxrefs=[]),
 SeqRecord(seq=Seq('GAGCGACCTCATGCTATACCTGAGAAAGCAACCTGACCTACAGGAAAGAGTTAC...CAT'), id=10007, name='VminG8H_tADH1', description='', dbxrefs=[]),
 SeqRecord(seq=Seq('GAGCGACCTCATGCTATACCTGAGAAAGCAACCTGACCTACAGGAAAGAGTTAC...CAT'), id=10008, name='OeuG8H_tADH1', description='', dbxrefs=[])]

## Getting the records from the database

In [36]:
g8h_from_csv_database = [] 
names = [name.name for name in G8H_templates]


# should be a function
for name in names: 
    record = get_ds_dna(str(name), 'ds_dna_plates' )
    g8h_from_csv_database.append(record)
g8h_from_csv_database

[SeqRecord(seq=Seq('GAGCGACCTCATGCTATACCTGAGAAAGCAACCTGACCTACAGGAAAGAGTTAC...CAT'), id=10000, name='CcalG8H_tADH1', description=nan, dbxrefs=[]),
 SeqRecord(seq=Seq('GAGCGACCTCATGCTATACCTGAGAAAGCAACCTGACCTACAGGAAAGAGTTAC...CAT'), id=10001, name='PcoG8H_tADH1', description=nan, dbxrefs=[]),
 SeqRecord(seq=Seq('GAGCGACCTCATGCTATACCTGAGAAAGCAACCTGACCTACAGGAAAGAGTTAC...CAT'), id=10002, name='CroG8H_tADH1', description=nan, dbxrefs=[]),
 SeqRecord(seq=Seq('GAGCGACCTCATGCTATACCTGAGAAAGCAACCTGACCTACAGGAAAGAGTTAC...CAT'), id=10003, name='OpumG8H_tADH1', description=nan, dbxrefs=[]),
 SeqRecord(seq=Seq('GAGCGACCTCATGCTATACCTGAGAAAGCAACCTGACCTACAGGAAAGAGTTAC...CAT'), id=10004, name='CacuG8H_tADH1', description=nan, dbxrefs=[]),
 SeqRecord(seq=Seq('GAGCGACCTCATGCTATACCTGAGAAAGCAACCTGACCTACAGGAAAGAGTTAC...CAT'), id=10005, name='RsepG8H_tADH1', description=nan, dbxrefs=[]),
 SeqRecord(seq=Seq('GAGCGACCTCATGCTATACCTGAGAAAGCAACCTGACCTACAGGAAAGAGTTAC...CAT'), id=10006, name='SmusG8H_tADH1', description=nan, dbxrefs=[]),
 SeqRecord(seq=Seq('GAGCGACCTCATGCTATACCTGAGAAAGCAACCTGACCTACAGGAAAGAGTTAC...CAT'), id=10007, name='VminG8H_tADH1', description=nan, dbxrefs=[]),
 SeqRecord(seq=Seq('GAGCGACCTCATGCTATACCTGAGAAAGCAACCTGACCTACAGGAAAGAGTTAC...CAT'), id=10008, name='OeuG8H_tADH1', description=nan, dbxrefs=[])]

## Lets add CPR to plate 1

In [37]:
CPR_templates

[SeqRecord(seq=Seq('ATGGACTCCTCATCGGAGAAGCTTTCCCCGTTCGACTTAATGACGGCAATCCTA...GAA'), id='pL_01_C7\\(pRS415-USER).0', name='AhuCPR_tCYC1', description='', dbxrefs=[]),
 SeqRecord(seq=Seq('ATGCAATCTACAACCTCCGTCAAGTTATCACCCTTTGACCTGATGACCGCATTA...GAA'), id='AanCPR_tCYC1', name='AanCPR_tCYC1', description='', dbxrefs=[]),
 SeqRecord(seq=Seq('ATGGATTCTTCTTCTGAAAAATTGTCTCCATTTGAATTGATGTCTGCTATTTTG...GAA'), id='CloCPR_tCYC1', name='CloCPR_tCYC1', description='', dbxrefs=[]),
 SeqRecord(seq=Seq('ATGCAGTCAAGTAGTGTAAAGGTGAGCACCTTCGACCTGATGAGTGCAATACTT...GAA'), id='pL_01_C7\\(pRS415-USER).0', name='CacCPR_tCYC1', description='', dbxrefs=[]),
 SeqRecord(seq=Seq('ATGGCTCAATTGGATACTTTGGATTTGGTTGTTTTGGCTGTTTTGTTGGTTGGT...GAA'), id='pL_01_C7\\(pRS415-USER).0', name='AniCPR_tCYC1', description='', dbxrefs=[]),
 SeqRecord(seq=Seq('ATGGATGAAACTGAAGCTACTTTGGGTACTCAACAAATTTCTGAAGCTTCTGAT...GAA'), id='pL_01_C7\\(pRS415-USER).0', name='CpoCPR_tCYC1', description='', dbxrefs=[]),
 SeqRecord(seq=Seq('ATGGACTCCACCTCAGAGAAGCTTTCACCGTTCGACTTCCTGACGGCAATCCTG...GAA'), id='pL_01_C7\\(pRS415-USER).0', name='OeuCPR_tCYC1', description='', dbxrefs=[]),
 SeqRecord(seq=Seq('ATGGATTCTTCTTCTGAAAAATTGTCTCCATTTGAATTGATGTCTGCTATTTTG...GAA'), id='pL_01_C7\\(pRS415-USER).0', name='RseCPR_tCYC1', description='', dbxrefs=[]),
 SeqRecord(seq=Seq('ATGACATCAGCTCTTTACGCCTCTGATCTATTTAAACAGCTGAAATCTATTATG...GAA'), id='AthATR1_tCYC1', name='AthATR1_tCYC1', description='', dbxrefs=[]),
 SeqRecord(seq=Seq('ATGGACTCATCCTCCGAGAAGTTGTCACCATTCGAACTTATGTCAGCAATTCTT...GAA'), id='CroCPR_tCYC1', name='CroCPR_tCYC1', description='', dbxrefs=[])]

Adding a unique id

In [38]:
add_unique_ids(CPR_templates)
CPR_templates

[SeqRecord(seq=Seq('ATGGACTCCTCATCGGAGAAGCTTTCCCCGTTCGACTTAATGACGGCAATCCTA...GAA'), id=10009, name='AhuCPR_tCYC1', description='', dbxrefs=[]),
 SeqRecord(seq=Seq('ATGCAATCTACAACCTCCGTCAAGTTATCACCCTTTGACCTGATGACCGCATTA...GAA'), id=10010, name='AanCPR_tCYC1', description='', dbxrefs=[]),
 SeqRecord(seq=Seq('ATGGATTCTTCTTCTGAAAAATTGTCTCCATTTGAATTGATGTCTGCTATTTTG...GAA'), id=10011, name='CloCPR_tCYC1', description='', dbxrefs=[]),
 SeqRecord(seq=Seq('ATGCAGTCAAGTAGTGTAAAGGTGAGCACCTTCGACCTGATGAGTGCAATACTT...GAA'), id=10012, name='CacCPR_tCYC1', description='', dbxrefs=[]),
 SeqRecord(seq=Seq('ATGGCTCAATTGGATACTTTGGATTTGGTTGTTTTGGCTGTTTTGTTGGTTGGT...GAA'), id=10013, name='AniCPR_tCYC1', description='', dbxrefs=[]),
 SeqRecord(seq=Seq('ATGGATGAAACTGAAGCTACTTTGGGTACTCAACAAATTTCTGAAGCTTCTGAT...GAA'), id=10014, name='CpoCPR_tCYC1', description='', dbxrefs=[]),
 SeqRecord(seq=Seq('ATGGACTCCACCTCAGAGAAGCTTTCACCGTTCGACTTCCTGACGGCAATCCTG...GAA'), id=10015, name='OeuCPR_tCYC1', description='', dbxrefs=[]),
 SeqRecord(seq=Seq('ATGGATTCTTCTTCTGAAAAATTGTCTCCATTTGAATTGATGTCTGCTATTTTG...GAA'), id=10016, name='RseCPR_tCYC1', description='', dbxrefs=[]),
 SeqRecord(seq=Seq('ATGACATCAGCTCTTTACGCCTCTGATCTATTTAAACAGCTGAAATCTATTATG...GAA'), id=10017, name='AthATR1_tCYC1', description='', dbxrefs=[]),
 SeqRecord(seq=Seq('ATGGACTCATCCTCCGAGAAGTTGTCACCATTCGAACTTATGTCAGCAATTCTT...GAA'), id=10018, name='CroCPR_tCYC1', description='', dbxrefs=[])]

In [39]:
add_annotations(CPR_templates)
CPR_templates

[SeqRecord(seq=Seq('ATGGACTCCTCATCGGAGAAGCTTTCCCCGTTCGACTTAATGACGGCAATCCTA...GAA'), id=10009, name='AhuCPR_tCYC1', description='', dbxrefs=[]),
 SeqRecord(seq=Seq('ATGCAATCTACAACCTCCGTCAAGTTATCACCCTTTGACCTGATGACCGCATTA...GAA'), id=10010, name='AanCPR_tCYC1', description='', dbxrefs=[]),
 SeqRecord(seq=Seq('ATGGATTCTTCTTCTGAAAAATTGTCTCCATTTGAATTGATGTCTGCTATTTTG...GAA'), id=10011, name='CloCPR_tCYC1', description='', dbxrefs=[]),
 SeqRecord(seq=Seq('ATGCAGTCAAGTAGTGTAAAGGTGAGCACCTTCGACCTGATGAGTGCAATACTT...GAA'), id=10012, name='CacCPR_tCYC1', description='', dbxrefs=[]),
 SeqRecord(seq=Seq('ATGGCTCAATTGGATACTTTGGATTTGGTTGTTTTGGCTGTTTTGTTGGTTGGT...GAA'), id=10013, name='AniCPR_tCYC1', description='', dbxrefs=[]),
 SeqRecord(seq=Seq('ATGGATGAAACTGAAGCTACTTTGGGTACTCAACAAATTTCTGAAGCTTCTGAT...GAA'), id=10014, name='CpoCPR_tCYC1', description='', dbxrefs=[]),
 SeqRecord(seq=Seq('ATGGACTCCACCTCAGAGAAGCTTTCACCGTTCGACTTCCTGACGGCAATCCTG...GAA'), id=10015, name='OeuCPR_tCYC1', description='', dbxrefs=[]),
 SeqRecord(seq=Seq('ATGGATTCTTCTTCTGAAAAATTGTCTCCATTTGAATTGATGTCTGCTATTTTG...GAA'), id=10016, name='RseCPR_tCYC1', description='', dbxrefs=[]),
 SeqRecord(seq=Seq('ATGACATCAGCTCTTTACGCCTCTGATCTATTTAAACAGCTGAAATCTATTATG...GAA'), id=10017, name='AthATR1_tCYC1', description='', dbxrefs=[]),
 SeqRecord(seq=Seq('ATGGACTCATCCTCCGAGAAGTTGTCACCATTCGAACTTATGTCAGCAATTCTT...GAA'), id=10018, name='CroCPR_tCYC1', description='', dbxrefs=[])]

In [40]:
get_plate(1, ds_DNA_plates)

,ID,name,date,plate,row,col,size,seq,concentration,features,location,reference,stock,comments,description
96,NaN,NaN,NaN,1,A,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
97,NaN,NaN,NaN,1,A,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98,NaN,NaN,NaN,1,A,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99,NaN,NaN,NaN,1,A,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100,NaN,NaN,NaN,1,A,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
187,NaN,NaN,NaN,1,H,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
188,NaN,NaN,NaN,1,H,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
189,NaN,NaN,NaN,1,H,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
190,NaN,NaN,NaN,1,H,11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
191,NaN,NaN,NaN,1,H,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [41]:
# lets add the sequences to plate 1 which is at index 96

In [42]:
add_sequences_to_dataframe(CPR_templates,ds_DNA_plates, index= 96 )

In [43]:
get_plate(1, ds_DNA_plates).head(20)

,ID,name,date,plate,row,col,size,seq,concentration,features,location,reference,stock,comments,description
96,10009.0,AhuCPR_tCYC1,08-12-2022,1,A,1,2328.0,ATGGACTCCTCATCGGAGAAGCTTTCCCCGTTCGACTTAATGACGG...,,"[SeqFeature(FeatureLocation(ExactPosition(0), ...",NaN,,,,
97,10010.0,AanCPR_tCYC1,08-12-2022,1,A,2,2298.0,ATGCAATCTACAACCTCCGTCAAGTTATCACCCTTTGACCTGATGA...,,"[SeqFeature(FeatureLocation(ExactPosition(0), ...",NaN,,,,
98,10011.0,CloCPR_tCYC1,08-12-2022,1,A,3,2328.0,ATGGATTCTTCTTCTGAAAAATTGTCTCCATTTGAATTGATGTCTG...,,"[SeqFeature(FeatureLocation(ExactPosition(0), ...",NaN,,,,
99,10012.0,CacCPR_tCYC1,08-12-2022,1,A,4,2310.0,ATGCAGTCAAGTAGTGTAAAGGTGAGCACCTTCGACCTGATGAGTG...,,"[SeqFeature(FeatureLocation(ExactPosition(0), ...",NaN,,,,
100,10013.0,AniCPR_tCYC1,08-12-2022,1,A,5,2268.0,ATGGCTCAATTGGATACTTTGGATTTGGTTGTTTTGGCTGTTTTGT...,,"[SeqFeature(FeatureLocation(ExactPosition(0), ...",NaN,,,,
101,10014.0,CpoCPR_tCYC1,08-12-2022,1,A,6,2223.0,ATGGATGAAACTGAAGCTACTTTGGGTACTCAACAAATTTCTGAAG...,,"[SeqFeature(FeatureLocation(ExactPosition(0), ...",NaN,,,,
102,10015.0,OeuCPR_tCYC1,08-12-2022,1,A,7,2310.0,ATGGACTCCACCTCAGAGAAGCTTTCACCGTTCGACTTCCTGACGG...,,"[SeqFeature(FeatureLocation(ExactPosition(0), ...",NaN,,,,
103,10016.0,RseCPR_tCYC1,08-12-2022,1,A,8,2328.0,ATGGATTCTTCTTCTGAAAAATTGTCTCCATTTGAATTGATGTCTG...,,"[SeqFeature(FeatureLocation(ExactPosition(0), ...",NaN,,,,
104,10017.0,AthATR1_tCYC1,08-12-2022,1,A,9,2262.0,ATGACATCAGCTCTTTACGCCTCTGATCTATTTAAACAGCTGAAAT...,,"[SeqFeature(FeatureLocation(ExactPosition(0), ...",NaN,,,,
105,10018.0,CroCPR_tCYC1,08-12-2022,1,A,10,2328.0,ATGGACTCATCCTCCGAGAAGTTGTCACCATTCGAACTTATGTCAG...,,"[SeqFeature(FeatureLocation(ExactPosition(0), ...",NaN,,,,
106,NaN,NaN,NaN,1,A,11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
107,NaN,NaN,NaN,1,A,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
108,NaN,NaN,NaN,1,B,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
109,NaN,NaN,NaN,1,B,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
110,NaN,NaN,NaN,1,B,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
111,NaN,NaN,NaN,1,B,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
112,NaN,NaN,NaN,1,B,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
113,NaN,NaN,NaN,1,B,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
114,NaN,NaN,NaN,1,B,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
115,NaN,NaN,NaN,1,B,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [64]:
# Lets add it to the database 
update_database(ds_DNA_plates, 'ds_dna_plates')

### Quick and dirty combinatorial library

In [65]:
genes = G8H_templates
genes

[SeqRecord(seq=Seq('GAGCGACCTCATGCTATACCTGAGAAAGCAACCTGACCTACAGGAAAGAGTTAC...CAT'), id=10000, name='CcalG8H_tADH1', description='', dbxrefs=[]),
 SeqRecord(seq=Seq('GAGCGACCTCATGCTATACCTGAGAAAGCAACCTGACCTACAGGAAAGAGTTAC...CAT'), id=10001, name='PcoG8H_tADH1', description='', dbxrefs=[]),
 SeqRecord(seq=Seq('GAGCGACCTCATGCTATACCTGAGAAAGCAACCTGACCTACAGGAAAGAGTTAC...CAT'), id=10002, name='CroG8H_tADH1', description='', dbxrefs=[]),
 SeqRecord(seq=Seq('GAGCGACCTCATGCTATACCTGAGAAAGCAACCTGACCTACAGGAAAGAGTTAC...CAT'), id=10003, name='OpumG8H_tADH1', description='', dbxrefs=[]),
 SeqRecord(seq=Seq('GAGCGACCTCATGCTATACCTGAGAAAGCAACCTGACCTACAGGAAAGAGTTAC...CAT'), id=10004, name='CacuG8H_tADH1', description='', dbxrefs=[]),
 SeqRecord(seq=Seq('GAGCGACCTCATGCTATACCTGAGAAAGCAACCTGACCTACAGGAAAGAGTTAC...CAT'), id=10005, name='RsepG8H_tADH1', description='', dbxrefs=[]),
 SeqRecord(seq=Seq('GAGCGACCTCATGCTATACCTGAGAAAGCAACCTGACCTACAGGAAAGAGTTAC...CAT'), id=10006, name='SmusG8H_tADH1', description='', dbxrefs=[]),
 SeqRecord(seq=Seq('GAGCGACCTCATGCTATACCTGAGAAAGCAACCTGACCTACAGGAAAGAGTTAC...CAT'), id=10007, name='VminG8H_tADH1', description='', dbxrefs=[]),
 SeqRecord(seq=Seq('GAGCGACCTCATGCTATACCTGAGAAAGCAACCTGACCTACAGGAAAGAGTTAC...CAT'), id=10008, name='OeuG8H_tADH1', description='', dbxrefs=[])]

In [66]:
pCPR_sites =[]
for seq_record in SeqIO.parse('../data/promoter_gb_files/pG8H_sites.gb', format= 'gb'):
    pCPR_sites.append(seq_record)

In [67]:
pCPR_sites

[SeqRecord(seq=Seq('CAGCATTTTCAAAGGTGTGTTCTTCGTCAGACATGTTTTAGTGTGTGAATGAAA...ATA'), id='seq_DPrPIMvy', name='pCYC1', description='', dbxrefs=[]),
 SeqRecord(seq=Seq('AATCCTACTCTTGCCGTTGCCATCCAAAATGAGCTAGAAGGTGGATTAACAAAT...ATA'), id='seq_8wWqUcpf', name='pENO2', description='', dbxrefs=[]),
 SeqRecord(seq=Seq('CACATGTCGACGAGTTTGTCATCGAATCCGTAATGAAGGCGCAAGAAAAACTAG...AAC'), id='seq_Bs85fGcK', name='pPCK1', description='', dbxrefs=[]),
 SeqRecord(seq=Seq('GTACTGCTGGCCATTTTTATTCAGGTTATTTGCGATTAGGTTGGGGTTTGTGTT...GCA'), id='seq_NFnLfXI8', name='pRPL15B', description='', dbxrefs=[])]

In [68]:
from  pydna.dseqrecord import Dseqrecord

In [69]:
promoter_names = [name.name for name in pCPR_sites]
genes_names = [name.name for name in genes]

list_of_names = [promoter_names, genes_names]
list_of_names

[['pCYC1', 'pENO2', 'pPCK1', 'pRPL15B'],
 ['CcalG8H_tADH1',
  'PcoG8H_tADH1',
  'CroG8H_tADH1',
  'OpumG8H_tADH1',
  'CacuG8H_tADH1',
  'RsepG8H_tADH1',
  'SmusG8H_tADH1',
  'VminG8H_tADH1',
  'OeuG8H_tADH1']]

In [70]:
promoter_seq = [Dseqrecord(seq) for seq in pCPR_sites]
genes_seq = [Dseqrecord(seq )for seq in genes]


list_of_seqs = [promoter_seq, genes_seq]
list_of_seqs

[[Dseqrecord(-987), Dseqrecord(-1000), Dseqrecord(-1000), Dseqrecord(-980)],
 [Dseqrecord(-1803),
  Dseqrecord(-1370),
  Dseqrecord(-1695),
  Dseqrecord(-1860),
  Dseqrecord(-1827),
  Dseqrecord(-1803),
  Dseqrecord(-1809),
  Dseqrecord(-1803),
  Dseqrecord(-1803)]]

In [71]:
for ids in genes_seq: 
    ids.id = str(ids.id)

In [72]:
genes_seq[0].id

'10000'

In [73]:
pad = Dseqrecord('ATCGCTAGCTG')

In [74]:
from constrain.design.combinatorial_design import DesignAssembly

In [75]:
%%time
dummy_assembly = DesignAssembly(list_of_seqs, list_of_names, pad , 1 )

CPU times: user 127 ms, sys: 3.51 ms, total: 130 ms
Wall time: 129 ms

In [76]:
primers = dummy_assembly.primer_list_to_dataframe()
primers

,ID,Anneals to,Sequence,Annealing temperature,Length,Price(DKK)
0,F001,pCYC1,"(C, A, G, C, A, T, T, T, T, C, A, A, A, G, G, ...",56.02,19,34.2
1,F002,CcalG8H_tADH1,"(C, A, C, T, A, A, A, T, T, A, A, T, A, A, T, ...",56.95,39,70.2
2,F003,PcoG8H_tADH1,"(C, A, C, T, A, A, A, T, T, A, A, T, A, A, T, ...",56.95,39,70.2
3,F004,CroG8H_tADH1,"(C, A, C, T, A, A, A, T, T, A, A, T, A, A, T, ...",56.95,39,70.2
4,F005,OpumG8H_tADH1,"(C, A, C, T, A, A, A, T, T, A, A, T, A, A, T, ...",56.95,39,70.2
...,...,...,...,...,...,...
68,R069,pRPL15B,"(C, A, T, G, A, G, G, T, C, G, C, T, C, C, A, ...",55.21,39,70.2
69,R070,pRPL15B,"(C, A, T, G, A, G, G, T, C, G, C, T, C, C, A, ...",55.21,39,70.2
70,R071,pRPL15B,"(C, A, T, G, A, G, G, T, C, G, C, T, C, C, A, ...",55.21,39,70.2
71,R072,pRPL15B,"(C, A, T, G, A, G, G, T, C, G, C, T, C, C, A, ...",55.21,39,70.2
72,R073,pRPL15B,"(C, A, T, G, A, G, G, T, C, G, C, T, C, C, A, ...",55.21,39,70.2

In [77]:
list_of_primers =[]
for index, row in primers.iterrows():
    record = SeqRecord(Seq(row['Sequence']), name = row['Anneals to']+'_'+row['ID'])
    list_of_primers.append(record)
list_of_primers

[SeqRecord(seq=Seq('CAGCATTTTCAAAGGTGTG'), id='<unknown id>', name='pCYC1_F001', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('CACTAAATTAATAATCGCTAGCTGGAGCGACCTCATGCT'), id='<unknown id>', name='CcalG8H_tADH1_F002', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('CACTAAATTAATAATCGCTAGCTGGAGCGACCTCATGCT'), id='<unknown id>', name='PcoG8H_tADH1_F003', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('CACTAAATTAATAATCGCTAGCTGGAGCGACCTCATGCT'), id='<unknown id>', name='CroG8H_tADH1_F004', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('CACTAAATTAATAATCGCTAGCTGGAGCGACCTCATGCT'), id='<unknown id>', name='OpumG8H_tADH1_F005', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('CACTAAATTAATAATCGCTAGCTGGAGCGACCTCATGCT'), id='<unknown id>', name='CacuG8H_tADH1_F006', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('CACTAAATTAATAATCGCTAGCTGGAGCGACCTCATGCT'), id='<unknown id>', name='RsepG8H_tADH1_F007', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('CACTAAATTAATAATCGCTAGCTGGAGCGACCTCATGCT'), id='<unknown id>', name='SmusG8H_tADH1_F008', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('CACTAAATTAATAATCGCTAGCTGGAGCGACCTCATGCT'), id='<unknown id>', name='VminG8H_tADH1_F009', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('CACTAAATTAATAATCGCTAGCTGGAGCGACCTCATGCT'), id='<unknown id>', name='OeuG8H_tADH1_F010', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('AATCCTACTCTTGCCG'), id='<unknown id>', name='pENO2_F011', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('ACATACAATAATAATCGCTAGCTGGAGCGACCTCATGCT'), id='<unknown id>', name='CcalG8H_tADH1_F012', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('ACATACAATAATAATCGCTAGCTGGAGCGACCTCATGCT'), id='<unknown id>', name='PcoG8H_tADH1_F013', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('ACATACAATAATAATCGCTAGCTGGAGCGACCTCATGCT'), id='<unknown id>', name='CroG8H_tADH1_F014', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('ACATACAATAATAATCGCTAGCTGGAGCGACCTCATGCT'), id='<unknown id>', name='OpumG8H_tADH1_F015', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('ACATACAATAATAATCGCTAGCTGGAGCGACCTCATGCT'), id='<unknown id>', name='CacuG8H_tADH1_F016', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('ACATACAATAATAATCGCTAGCTGGAGCGACCTCATGCT'), id='<unknown id>', name='RsepG8H_tADH1_F017', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('ACATACAATAATAATCGCTAGCTGGAGCGACCTCATGCT'), id='<unknown id>', name='SmusG8H_tADH1_F018', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('ACATACAATAATAATCGCTAGCTGGAGCGACCTCATGCT'), id='<unknown id>', name='VminG8H_tADH1_F019', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('ACATACAATAATAATCGCTAGCTGGAGCGACCTCATGCT'), id='<unknown id>', name='OeuG8H_tADH1_F020', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('CACATGTCGACGAGTTTG'), id='<unknown id>', name='pPCK1_F021', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('ATAAAATAACAACATCGCTAGCTGGAGCGACCTCATGCT'), id='<unknown id>', name='CcalG8H_tADH1_F022', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('ATAAAATAACAACATCGCTAGCTGGAGCGACCTCATGCT'), id='<unknown id>', name='PcoG8H_tADH1_F023', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('ATAAAATAACAACATCGCTAGCTGGAGCGACCTCATGCT'), id='<unknown id>', name='CroG8H_tADH1_F024', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('ATAAAATAACAACATCGCTAGCTGGAGCGACCTCATGCT'), id='<unknown id>', name='OpumG8H_tADH1_F025', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('ATAAAATAACAACATCGCTAGCTGGAGCGACCTCATGCT'), id='<unknown id>', name='CacuG8H_tADH1_F026', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('ATAAAATAACAACATCGCTAGCTGGAGCGACCTCATGCT'), id='<unknown id>', name='RsepG8H_tADH1_F027', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('ATAAAATAACAACATCGCTAGCTGGAGCGACCTCATGCT'), id='<unknown id>', name='SmusG8H_tADH1_F028', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('ATAAAATAACAACATCGCTAGCTGGAGCGACCTCATGCT'), id='<unknown id>', name='VminG8H_tADH1_F029', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('ATAAAATAACAACATCGCTAGCTGGAGCGACCTCATGCT'), id='<unknown id>', name='OeuG8H_tADH1_F030', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('GTACTGCTGGCCATT'), id='<unknown id>', name='pRPL15B_F031', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('TACCACACAAGCAATCGCTAGCTGGAGCGACCTCATGCT'), id='<unknown id>', name='CcalG8H_tADH1_F032', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('TACCACACAAGCAATCGCTAGCTGGAGCGACCTCATGCT'), id='<unknown id>', name='PcoG8H_tADH1_F033', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('TACCACACAAGCAATCGCTAGCTGGAGCGACCTCATGCT'), id='<unknown id>', name='CroG8H_tADH1_F034', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('TACCACACAAGCAATCGCTAGCTGGAGCGACCTCATGCT'), id='<unknown id>', name='OpumG8H_tADH1_F035', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('TACCACACAAGCAATCGCTAGCTGGAGCGACCTCATGCT'), id='<unknown id>', name='CacuG8H_tADH1_F036', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('TACCACACAAGCAATCGCTAGCTGGAGCGACCTCATGCT'), id='<unknown id>', name='RsepG8H_tADH1_F037', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('TACCACACAAGCAATCGCTAGCTGGAGCGACCTCATGCT'), id='<unknown id>', name='SmusG8H_tADH1_F038', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('TACCACACAAGCAATCGCTAGCTGGAGCGACCTCATGCT'), id='<unknown id>', name='VminG8H_tADH1_F039', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('TACCACACAAGCAATCGCTAGCTGGAGCGACCTCATGCT'), id='<unknown id>', name='OeuG8H_tADH1_F040', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('CATGAGGTCGCTCCAGCTAGCGATTATTAATTTAGTGTGTGTATTTGTG'), id='<unknown id>', name='pCYC1_R041', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('ATGGATTACTTAACTATTGTCCT'), id='<unknown id>', name='CcalG8H_tADH1_R042', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('CATGAGGTCGCTCCAGCTAGCGATTATTAATTTAGTGTGTGTATTTGTG'), id='<unknown id>', name='pCYC1_R043', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('ATGTTGGTTGAAGCTGC'), id='<unknown id>', name='PcoG8H_tADH1_R044', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('CATGAGGTCGCTCCAGCTAGCGATTATTAATTTAGTGTGTGTATTTGTG'), id='<unknown id>', name='pCYC1_R045', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('ATGGATTACCTTACAATTATCC'), id='<unknown id>', name='CroG8H_tADH1_R046', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('CATGAGGTCGCTCCAGCTAGCGATTATTAATTTAGTGTGTGTATTTGTG'), id='<unknown id>', name='pCYC1_R047', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('ATGCGTATCTTAGATTCAGAAG'), id='<unknown id>', name='OpumG8H_tADH1_R048', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('CATGAGGTCGCTCCAGCTAGCGATTATTAATTTAGTGTGTGTATTTGTG'), id='<unknown id>', name='pCYC1_R049', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('ATGGACATAATGGACTTTATGT'), id='<unknown id>', name='CacuG8H_tADH1_R050', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('ATGGATTACTTGACTATCACG'), id='<unknown id>', name='RsepG8H_tADH1_R051', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('CATGAGGTCGCTCCAGCTAGCGATTATTAATTTAGTGTGTGTATTTGTG'), id='<unknown id>', name='pCYC1_R052', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('ATGGACTTTGACTTCTTGAC'), id='<unknown id>', name='SmusG8H_tADH1_R053', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('ATGGATTACTTGACGATCG'), id='<unknown id>', name='VminG8H_tADH1_R054', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('ATGGACTTCTTAACAATCGTTT'), id='<unknown id>', name='OeuG8H_tADH1_R055', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('CATGAGGTCGCTCCAGCTAGCGATTATTATTGTATGTTATAGTATTAGTTGC'), id='<unknown id>', name='pENO2_R056', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('CATGAGGTCGCTCCAGCTAGCGATTATTATTGTATGTTATAGTATTAGTTGC'), id='<unknown id>', name='pENO2_R057', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('CATGAGGTCGCTCCAGCTAGCGATTATTATTGTATGTTATAGTATTAGTTGC'), id='<unknown id>', name='pENO2_R058', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('CATGAGGTCGCTCCAGCTAGCGATTATTATTGTATGTTATAGTATTAGTTGC'), id='<unknown id>', name='pENO2_R059', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('CATGAGGTCGCTCCAGCTAGCGATTATTATTGTATGTTATAGTATTAGTTGC'), id='<unknown id>', name='pENO2_R060', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('CATGAGGTCGCTCCAGCTAGCGATTATTATTGTATGTTATAGTATTAGTTGC'), id='<unknown id>', name='pENO2_R061', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('CATGAGGTCGCTCCAGCTAGCGATGTTGTTATTTTATTATGGAATAATTAGTTG'), id='<unknown id>', name='pPCK1_R062', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('CATGAGGTCGCTCCAGCTAGCGATGTTGTTATTTTATTATGGAATAATTAGTTG'), id='<unknown id>', name='pPCK1_R063', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('CATGAGGTCGCTCCAGCTAGCGATGTTGTTATTTTATTATGGAATAATTAGTTG'), id='<unknown id>', name='pPCK1_R064', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('CATGAGGTCGCTCCAGCTAGCGATGTTGTTATTTTATTATGGAATAATTAGTTG'), id='<unknown id>', name='pPCK1_R065', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('CATGAGGTCGCTCCAGCTAGCGATGTTGTTATTTTATTATGGAATAATTAGTTG'), id='<unknown id>', name='pPCK1_R066', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('CATGAGGTCGCTCCAGCTAGCGATGTTGTTATTTTATTATGGAATAATTAGTTG'), id='<unknown id>', name='pPCK1_R067', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('CATGAGGTCGCTCCAGCTAGCGATTGCTTGTGTGGTAGG'), id='<unknown id>', name='pRPL15B_R068', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('CATGAGGTCGCTCCAGCTAGCGATTGCTTGTGTGGTAGG'), id='<unknown id>', name='pRPL15B_R069', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('CATGAGGTCGCTCCAGCTAGCGATTGCTTGTGTGGTAGG'), id='<unknown id>', name='pRPL15B_R070', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('CATGAGGTCGCTCCAGCTAGCGATTGCTTGTGTGGTAGG'), id='<unknown id>', name='pRPL15B_R071', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('CATGAGGTCGCTCCAGCTAGCGATTGCTTGTGTGGTAGG'), id='<unknown id>', name='pRPL15B_R072', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('CATGAGGTCGCTCCAGCTAGCGATTGCTTGTGTGGTAGG'), id='<unknown id>', name='pRPL15B_R073', description='<unknown description>', dbxrefs=[])]

In [78]:
add_unique_ids(list_of_primers )
add_annotations(list_of_primers)

In [79]:
list_of_primers

[SeqRecord(seq=Seq('CAGCATTTTCAAAGGTGTG'), id=10019, name='pCYC1_F001', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('CACTAAATTAATAATCGCTAGCTGGAGCGACCTCATGCT'), id=10020, name='CcalG8H_tADH1_F002', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('CACTAAATTAATAATCGCTAGCTGGAGCGACCTCATGCT'), id=10021, name='PcoG8H_tADH1_F003', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('CACTAAATTAATAATCGCTAGCTGGAGCGACCTCATGCT'), id=10022, name='CroG8H_tADH1_F004', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('CACTAAATTAATAATCGCTAGCTGGAGCGACCTCATGCT'), id=10023, name='OpumG8H_tADH1_F005', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('CACTAAATTAATAATCGCTAGCTGGAGCGACCTCATGCT'), id=10024, name='CacuG8H_tADH1_F006', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('CACTAAATTAATAATCGCTAGCTGGAGCGACCTCATGCT'), id=10025, name='RsepG8H_tADH1_F007', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('CACTAAATTAATAATCGCTAGCTGGAGCGACCTCATGCT'), id=10026, name='SmusG8H_tADH1_F008', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('CACTAAATTAATAATCGCTAGCTGGAGCGACCTCATGCT'), id=10027, name='VminG8H_tADH1_F009', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('CACTAAATTAATAATCGCTAGCTGGAGCGACCTCATGCT'), id=10028, name='OeuG8H_tADH1_F010', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('AATCCTACTCTTGCCG'), id=10029, name='pENO2_F011', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('ACATACAATAATAATCGCTAGCTGGAGCGACCTCATGCT'), id=10030, name='CcalG8H_tADH1_F012', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('ACATACAATAATAATCGCTAGCTGGAGCGACCTCATGCT'), id=10031, name='PcoG8H_tADH1_F013', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('ACATACAATAATAATCGCTAGCTGGAGCGACCTCATGCT'), id=10032, name='CroG8H_tADH1_F014', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('ACATACAATAATAATCGCTAGCTGGAGCGACCTCATGCT'), id=10033, name='OpumG8H_tADH1_F015', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('ACATACAATAATAATCGCTAGCTGGAGCGACCTCATGCT'), id=10034, name='CacuG8H_tADH1_F016', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('ACATACAATAATAATCGCTAGCTGGAGCGACCTCATGCT'), id=10035, name='RsepG8H_tADH1_F017', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('ACATACAATAATAATCGCTAGCTGGAGCGACCTCATGCT'), id=10036, name='SmusG8H_tADH1_F018', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('ACATACAATAATAATCGCTAGCTGGAGCGACCTCATGCT'), id=10037, name='VminG8H_tADH1_F019', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('ACATACAATAATAATCGCTAGCTGGAGCGACCTCATGCT'), id=10038, name='OeuG8H_tADH1_F020', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('CACATGTCGACGAGTTTG'), id=10039, name='pPCK1_F021', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('ATAAAATAACAACATCGCTAGCTGGAGCGACCTCATGCT'), id=10040, name='CcalG8H_tADH1_F022', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('ATAAAATAACAACATCGCTAGCTGGAGCGACCTCATGCT'), id=10041, name='PcoG8H_tADH1_F023', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('ATAAAATAACAACATCGCTAGCTGGAGCGACCTCATGCT'), id=10042, name='CroG8H_tADH1_F024', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('ATAAAATAACAACATCGCTAGCTGGAGCGACCTCATGCT'), id=10043, name='OpumG8H_tADH1_F025', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('ATAAAATAACAACATCGCTAGCTGGAGCGACCTCATGCT'), id=10044, name='CacuG8H_tADH1_F026', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('ATAAAATAACAACATCGCTAGCTGGAGCGACCTCATGCT'), id=10045, name='RsepG8H_tADH1_F027', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('ATAAAATAACAACATCGCTAGCTGGAGCGACCTCATGCT'), id=10046, name='SmusG8H_tADH1_F028', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('ATAAAATAACAACATCGCTAGCTGGAGCGACCTCATGCT'), id=10047, name='VminG8H_tADH1_F029', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('ATAAAATAACAACATCGCTAGCTGGAGCGACCTCATGCT'), id=10048, name='OeuG8H_tADH1_F030', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('GTACTGCTGGCCATT'), id=10049, name='pRPL15B_F031', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('TACCACACAAGCAATCGCTAGCTGGAGCGACCTCATGCT'), id=10050, name='CcalG8H_tADH1_F032', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('TACCACACAAGCAATCGCTAGCTGGAGCGACCTCATGCT'), id=10051, name='PcoG8H_tADH1_F033', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('TACCACACAAGCAATCGCTAGCTGGAGCGACCTCATGCT'), id=10052, name='CroG8H_tADH1_F034', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('TACCACACAAGCAATCGCTAGCTGGAGCGACCTCATGCT'), id=10053, name='OpumG8H_tADH1_F035', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('TACCACACAAGCAATCGCTAGCTGGAGCGACCTCATGCT'), id=10054, name='CacuG8H_tADH1_F036', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('TACCACACAAGCAATCGCTAGCTGGAGCGACCTCATGCT'), id=10055, name='RsepG8H_tADH1_F037', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('TACCACACAAGCAATCGCTAGCTGGAGCGACCTCATGCT'), id=10056, name='SmusG8H_tADH1_F038', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('TACCACACAAGCAATCGCTAGCTGGAGCGACCTCATGCT'), id=10057, name='VminG8H_tADH1_F039', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('TACCACACAAGCAATCGCTAGCTGGAGCGACCTCATGCT'), id=10058, name='OeuG8H_tADH1_F040', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('CATGAGGTCGCTCCAGCTAGCGATTATTAATTTAGTGTGTGTATTTGTG'), id=10059, name='pCYC1_R041', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('ATGGATTACTTAACTATTGTCCT'), id=10060, name='CcalG8H_tADH1_R042', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('CATGAGGTCGCTCCAGCTAGCGATTATTAATTTAGTGTGTGTATTTGTG'), id=10061, name='pCYC1_R043', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('ATGTTGGTTGAAGCTGC'), id=10062, name='PcoG8H_tADH1_R044', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('CATGAGGTCGCTCCAGCTAGCGATTATTAATTTAGTGTGTGTATTTGTG'), id=10063, name='pCYC1_R045', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('ATGGATTACCTTACAATTATCC'), id=10064, name='CroG8H_tADH1_R046', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('CATGAGGTCGCTCCAGCTAGCGATTATTAATTTAGTGTGTGTATTTGTG'), id=10065, name='pCYC1_R047', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('ATGCGTATCTTAGATTCAGAAG'), id=10066, name='OpumG8H_tADH1_R048', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('CATGAGGTCGCTCCAGCTAGCGATTATTAATTTAGTGTGTGTATTTGTG'), id=10067, name='pCYC1_R049', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('ATGGACATAATGGACTTTATGT'), id=10068, name='CacuG8H_tADH1_R050', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('ATGGATTACTTGACTATCACG'), id=10069, name='RsepG8H_tADH1_R051', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('CATGAGGTCGCTCCAGCTAGCGATTATTAATTTAGTGTGTGTATTTGTG'), id=10070, name='pCYC1_R052', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('ATGGACTTTGACTTCTTGAC'), id=10071, name='SmusG8H_tADH1_R053', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('ATGGATTACTTGACGATCG'), id=10072, name='VminG8H_tADH1_R054', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('ATGGACTTCTTAACAATCGTTT'), id=10073, name='OeuG8H_tADH1_R055', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('CATGAGGTCGCTCCAGCTAGCGATTATTATTGTATGTTATAGTATTAGTTGC'), id=10074, name='pENO2_R056', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('CATGAGGTCGCTCCAGCTAGCGATTATTATTGTATGTTATAGTATTAGTTGC'), id=10075, name='pENO2_R057', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('CATGAGGTCGCTCCAGCTAGCGATTATTATTGTATGTTATAGTATTAGTTGC'), id=10076, name='pENO2_R058', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('CATGAGGTCGCTCCAGCTAGCGATTATTATTGTATGTTATAGTATTAGTTGC'), id=10077, name='pENO2_R059', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('CATGAGGTCGCTCCAGCTAGCGATTATTATTGTATGTTATAGTATTAGTTGC'), id=10078, name='pENO2_R060', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('CATGAGGTCGCTCCAGCTAGCGATTATTATTGTATGTTATAGTATTAGTTGC'), id=10079, name='pENO2_R061', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('CATGAGGTCGCTCCAGCTAGCGATGTTGTTATTTTATTATGGAATAATTAGTTG'), id=10080, name='pPCK1_R062', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('CATGAGGTCGCTCCAGCTAGCGATGTTGTTATTTTATTATGGAATAATTAGTTG'), id=10081, name='pPCK1_R063', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('CATGAGGTCGCTCCAGCTAGCGATGTTGTTATTTTATTATGGAATAATTAGTTG'), id=10082, name='pPCK1_R064', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('CATGAGGTCGCTCCAGCTAGCGATGTTGTTATTTTATTATGGAATAATTAGTTG'), id=10083, name='pPCK1_R065', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('CATGAGGTCGCTCCAGCTAGCGATGTTGTTATTTTATTATGGAATAATTAGTTG'), id=10084, name='pPCK1_R066', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('CATGAGGTCGCTCCAGCTAGCGATGTTGTTATTTTATTATGGAATAATTAGTTG'), id=10085, name='pPCK1_R067', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('CATGAGGTCGCTCCAGCTAGCGATTGCTTGTGTGGTAGG'), id=10086, name='pRPL15B_R068', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('CATGAGGTCGCTCCAGCTAGCGATTGCTTGTGTGGTAGG'), id=10087, name='pRPL15B_R069', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('CATGAGGTCGCTCCAGCTAGCGATTGCTTGTGTGGTAGG'), id=10088, name='pRPL15B_R070', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('CATGAGGTCGCTCCAGCTAGCGATTGCTTGTGTGGTAGG'), id=10089, name='pRPL15B_R071', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('CATGAGGTCGCTCCAGCTAGCGATTGCTTGTGTGGTAGG'), id=10090, name='pRPL15B_R072', description='<unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('CATGAGGTCGCTCCAGCTAGCGATTGCTTGTGTGGTAGG'), id=10091, name='pRPL15B_R073', description='<unknown description>', dbxrefs=[])]

In [80]:
primers_df = pd.read_csv('../data/csv_database/primer_plate.csv', index_col=False) 
primers_df

,ID,name,plate,row,col,size,seq,concentration,features,location,reference,reference.1,stock,comments
0,NaN,NaN,0,A,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,0,A,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,0,A,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,0,A,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,0,A,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
955,NaN,NaN,9,H,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
956,NaN,NaN,9,H,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
957,NaN,NaN,9,H,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
958,NaN,NaN,9,H,11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
959,NaN,NaN,9,H,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [81]:
add_sequences_to_dataframe(list_of_primers,primers_df )

In [82]:
primers_df

,ID,name,plate,row,col,size,seq,concentration,features,location,reference,reference.1,stock,comments,description,date
0,10019.0,pCYC1_F001,0,A,1,19.0,CAGCATTTTCAAAGGTGTG,,[],NaN,,NaN,,,<unknown description>,08-12-2022
1,10020.0,CcalG8H_tADH1_F002,0,A,2,39.0,CACTAAATTAATAATCGCTAGCTGGAGCGACCTCATGCT,,[],NaN,,NaN,,,<unknown description>,08-12-2022
2,10021.0,PcoG8H_tADH1_F003,0,A,3,39.0,CACTAAATTAATAATCGCTAGCTGGAGCGACCTCATGCT,,[],NaN,,NaN,,,<unknown description>,08-12-2022
3,10022.0,CroG8H_tADH1_F004,0,A,4,39.0,CACTAAATTAATAATCGCTAGCTGGAGCGACCTCATGCT,,[],NaN,,NaN,,,<unknown description>,08-12-2022
4,10023.0,OpumG8H_tADH1_F005,0,A,5,39.0,CACTAAATTAATAATCGCTAGCTGGAGCGACCTCATGCT,,[],NaN,,NaN,,,<unknown description>,08-12-2022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
955,NaN,NaN,9,H,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
956,NaN,NaN,9,H,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
957,NaN,NaN,9,H,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
958,NaN,NaN,9,H,11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
959,NaN,NaN,9,H,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [83]:
## lets add to boxes 
primer_box = pd.read_csv('../data/csv_database/box_MASTER.csv', index_col = False)
primer_box

,ID,name,box,row,col,size,seq,concentration,features,location,reference,stock,comments
0,NaN,NaN,0,A,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,0,A,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,0,A,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,0,A,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,0,A,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
805,NaN,NaN,9,I,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
806,NaN,NaN,9,I,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
807,NaN,NaN,9,I,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
808,NaN,NaN,9,I,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
809,NaN,NaN,9,I,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [84]:
add_sequences_to_dataframe(list_of_primers,primer_box )

In [86]:
primer_box.head(50)

,ID,name,box,row,col,size,seq,concentration,features,location,reference,stock,comments,description,date
0,10019.0,pCYC1_F001,0,A,1,19.0,CAGCATTTTCAAAGGTGTG,,[],NaN,,,,<unknown description>,08-12-2022
1,10020.0,CcalG8H_tADH1_F002,0,A,2,39.0,CACTAAATTAATAATCGCTAGCTGGAGCGACCTCATGCT,,[],NaN,,,,<unknown description>,08-12-2022
2,10021.0,PcoG8H_tADH1_F003,0,A,3,39.0,CACTAAATTAATAATCGCTAGCTGGAGCGACCTCATGCT,,[],NaN,,,,<unknown description>,08-12-2022
3,10022.0,CroG8H_tADH1_F004,0,A,4,39.0,CACTAAATTAATAATCGCTAGCTGGAGCGACCTCATGCT,,[],NaN,,,,<unknown description>,08-12-2022
4,10023.0,OpumG8H_tADH1_F005,0,A,5,39.0,CACTAAATTAATAATCGCTAGCTGGAGCGACCTCATGCT,,[],NaN,,,,<unknown description>,08-12-2022
5,10024.0,CacuG8H_tADH1_F006,0,A,6,39.0,CACTAAATTAATAATCGCTAGCTGGAGCGACCTCATGCT,,[],NaN,,,,<unknown description>,08-12-2022
6,10025.0,RsepG8H_tADH1_F007,0,A,7,39.0,CACTAAATTAATAATCGCTAGCTGGAGCGACCTCATGCT,,[],NaN,,,,<unknown description>,08-12-2022
7,10026.0,SmusG8H_tADH1_F008,0,A,8,39.0,CACTAAATTAATAATCGCTAGCTGGAGCGACCTCATGCT,,[],NaN,,,,<unknown description>,08-12-2022
8,10027.0,VminG8H_tADH1_F009,0,A,9,39.0,CACTAAATTAATAATCGCTAGCTGGAGCGACCTCATGCT,,[],NaN,,,,<unknown description>,08-12-2022
9,10028.0,OeuG8H_tADH1_F010,0,B,1,39.0,CACTAAATTAATAATCGCTAGCTGGAGCGACCTCATGCT,,[],NaN,,,,<unknown description>,08-12-2022
10,10029.0,pENO2_F011,0,B,2,16.0,AATCCTACTCTTGCCG,,[],NaN,,,,<unknown description>,08-12-2022
11,10030.0,CcalG8H_tADH1_F012,0,B,3,39.0,ACATACAATAATAATCGCTAGCTGGAGCGACCTCATGCT,,[],NaN,,,,<unknown description>,08-12-2022
12,10031.0,PcoG8H_tADH1_F013,0,B,4,39.0,ACATACAATAATAATCGCTAGCTGGAGCGACCTCATGCT,,[],NaN,,,,<unknown description>,08-12-2022
13,10032.0,CroG8H_tADH1_F014,0,B,5,39.0,ACATACAATAATAATCGCTAGCTGGAGCGACCTCATGCT,,[],NaN,,,,<unknown description>,08-12-2022
14,10033.0,OpumG8H_tADH1_F015,0,B,6,39.0,ACATACAATAATAATCGCTAGCTGGAGCGACCTCATGCT,,[],NaN,,,,<unknown description>,08-12-2022
15,10034.0,CacuG8H_tADH1_F016,0,B,7,39.0,ACATACAATAATAATCGCTAGCTGGAGCGACCTCATGCT,,[],NaN,,,,<unknown description>,08-12-2022
16,10035.0,RsepG8H_tADH1_F017,0,B,8,39.0,ACATACAATAATAATCGCTAGCTGGAGCGACCTCATGCT,,[],NaN,,,,<unknown description>,08-12-2022
17,10036.0,SmusG8H_tADH1_F018,0,B,9,39.0,ACATACAATAATAATCGCTAGCTGGAGCGACCTCATGCT,,[],NaN,,,,<unknown description>,08-12-2022
18,10037.0,VminG8H_tADH1_F019,0,C,1,39.0,ACATACAATAATAATCGCTAGCTGGAGCGACCTCATGCT,,[],NaN,,,,<unknown description>,08-12-2022
19,10038.0,OeuG8H_tADH1_F020,0,C,2,39.0,ACATACAATAATAATCGCTAGCTGGAGCGACCTCATGCT,,[],NaN,,,,<unknown description>,08-12-2022
20,10039.0,pPCK1_F021,0,C,3,18.0,CACATGTCGACGAGTTTG,,[],NaN,,,,<unknown description>,08-12-2022
21,10040.0,CcalG8H_tADH1_F022,0,C,4,39.0,ATAAAATAACAACATCGCTAGCTGGAGCGACCTCATGCT,,[],NaN,,,,<unknown description>,08-12-2022
22,10041.0,PcoG8H_tADH1_F023,0,C,5,39.0,ATAAAATAACAACATCGCTAGCTGGAGCGACCTCATGCT,,[],NaN,,,,<unknown description>,08-12-2022
23,10042.0,CroG8H_tADH1_F024,0,C,6,39.0,ATAAAATAACAACATCGCTAGCTGGAGCGACCTCATGCT,,[],NaN,,,,<unknown description>,08-12-2022
24,10043.0,OpumG8H_tADH1_F025,0,C,7,39.0,ATAAAATAACAACATCGCTAGCTGGAGCGACCTCATGCT,,[],NaN,,,,<unknown description>,08-12-2022
25,10044.0,CacuG8H_tADH1_F026,0,C,8,39.0,ATAAAATAACAACATCGCTAGCTGGAGCGACCTCATGCT,,[],NaN,,,,<unknown description>,08-12-2022
26,10045.0,RsepG8H_tADH1_F027,0,C,9,39.0,ATAAAATAACAACATCGCTAGCTGGAGCGACCTCATGCT,,[],NaN,,,,<unknown description>,08-12-2022
27,10046.0,SmusG8H_tADH1_F028,0,D,1,39.0,ATAAAATAACAACATCGCTAGCTGGAGCGACCTCATGCT,,[],NaN,,,,<unknown description>,08-12-2022
28,10047.0,VminG8H_tADH1_F029,0,D,2,39.0,ATAAAATAACAACATCGCTAGCTGGAGCGACCTCATGCT,,[],NaN,,,,<unknown description>,08-12-2022
29,10048.0,OeuG8H_tADH1_F030,0,D,3,39.0,ATAAAATAACAACATCGCTAGCTGGAGCGACCTCATGCT,,[],NaN,,,,<unknown description>,08-12-2022
30,10049.0,pRPL15B_F031,0,D,4,15.0,GTACTGCTGGCCATT,,[],NaN,,,,<unknown description>,08-12-2022
31,10050.0,CcalG8H_tADH1_F032,0,D,5,39.0,TACCACACAAGCAATCGCTAGCTGGAGCGACCTCATGCT,,[],NaN,,,,<unknown description>,08-12-2022
32,10051.0,PcoG8H_tADH1_F033,0,D,6,39.0,TACCACACAAGCAATCGCTAGCTGGAGCGACCTCATGCT,,[],NaN,,,,<unknown description>,08-12-2022
33,10052.0,CroG8H_tADH1_F034,0,D,7,39.0,TACCACACAAGCAATCGCTAGCTGGAGCGACCTCATGCT,,[],NaN,,,,<unknown description>,08-12-2022
34,10053.0,OpumG8H_tADH1_F035,0,D,8,39.0,TACCACACAAGCAATCGCTAGCTGGAGCGACCTCATGCT,,[],NaN,,,,<unknown description>,08-12-2022
35,10054.0,CacuG8H_tADH1_F036,0,D,9,39.0,TACCACACAAGCAATCGCTAGCTGGAGCGACCTCATGCT,,[],NaN,,,,<unknown description>,08-12-2022
36,10055.0,RsepG8H_tADH1_F037,0,E,1,39.0,TACCACACAAGCAATCGCTAGCTGGAGCGACCTCATGCT,,[],NaN,,,,<unknown description>,08-12-2022
37,10056.0,SmusG8H_tADH1_F038,0,E,2,39.0,TACCACACAAGCAATCGCTAGCTGGAGCGACCTCATGCT,,[],NaN,,,,<unknown description>,08-12-2022
38,10057.0,VminG8H_tADH1_F039,0,E,3,39.0,TACCACACAAGCAATCGCTAGCTGGAGCGACCTCATGCT,,[],NaN,,,,<unknown description>,08-12-2022
39,10058.0,OeuG8H_tADH1_F040,0,E,4,39.0,TACCACACAAGCAATCGCTAGCTGGAGCGACCTCATGCT,,[],NaN,,,,<unknown description>,08-12-2022
40,10059.0,pCYC1_R041,0,E,5,49.0,CATGAGGTCGCTCCAGCTAGCGATTATTAATTTAGTGTGTGTATTTGTG,,[],NaN,,,,<unknown description>,08-12-2022
41,10060.0,CcalG8H_tADH1_R042,0,E,6,23.0,ATGGATTACTTAACTATTGTCCT,,[],NaN,,,,<unknown description>,08-12-2022
42,10061.0,pCYC1_R043,0,E,7,49.0,CATGAGGTCGCTCCAGCTAGCGATTATTAATTTAGTGTGTGTATTTGTG,,[],NaN,,,,<unknown description>,08-12-2022
43,10062.0,PcoG8H_tADH1_R044,0,E,8,17.0,ATGTTGGTTGAAGCTGC,,[],NaN,,,,<unknown description>,08-12-2022
44,10063.0,pCYC1_R045,0,E,9,49.0,CATGAGGTCGCTCCAGCTAGCGATTATTAATTTAGTGTGTGTATTTGTG,,[],NaN,,,,<unknown description>,08-12-2022
45,10064.0,CroG8H_tADH1_R046,0,F,1,22.0,ATGGATTACCTTACAATTATCC,,[],NaN,,,,<unknown description>,08-12-2022
46,10065.0,pCYC1_R047,0,F,2,49.0,CATGAGGTCGCTCCAGCTAGCGATTATTAATTTAGTGTGTGTATTTGTG,,[],NaN,,,,<unknown description>,08-12-2022
47,10066.0,OpumG8H_tADH1_R048,0,F,3,22.0,ATGCGTATCTTAGATTCAGAAG,,[],NaN,,,,<unknown description>,08-12-2022
48,10067.0,pCYC1_R049,0,F,4,49.0,CATGAGGTCGCTCCAGCTAGCGATTATTAATTTAGTGTGTGTATTTGTG,,[],NaN,,,,<unknown description>,08-12-2022
49,10068.0,CacuG8H_tADH1_R050,0,F,5,22.0,ATGGACATAATGGACTTTATGT,,[],NaN,,,,<unknown description>,08-12-2022

In [93]:
get_box(0, primer_box)

,ID,name,box,row,col,size,seq,concentration,features,location,reference,stock,comments,description,date
0,10019.0,pCYC1_F001,0,A,1,19.0,CAGCATTTTCAAAGGTGTG,,[],NaN,,,,<unknown description>,08-12-2022
1,10020.0,CcalG8H_tADH1_F002,0,A,2,39.0,CACTAAATTAATAATCGCTAGCTGGAGCGACCTCATGCT,,[],NaN,,,,<unknown description>,08-12-2022
2,10021.0,PcoG8H_tADH1_F003,0,A,3,39.0,CACTAAATTAATAATCGCTAGCTGGAGCGACCTCATGCT,,[],NaN,,,,<unknown description>,08-12-2022
3,10022.0,CroG8H_tADH1_F004,0,A,4,39.0,CACTAAATTAATAATCGCTAGCTGGAGCGACCTCATGCT,,[],NaN,,,,<unknown description>,08-12-2022
4,10023.0,OpumG8H_tADH1_F005,0,A,5,39.0,CACTAAATTAATAATCGCTAGCTGGAGCGACCTCATGCT,,[],NaN,,,,<unknown description>,08-12-2022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76,NaN,NaN,0,I,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
77,NaN,NaN,0,I,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
78,NaN,NaN,0,I,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
79,NaN,NaN,0,I,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
80,NaN,NaN,0,I,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [98]:
update_database(primer_box, 'primer_box1_')

In [104]:
def get_dna_from_id(id:str, database_name:str)-> SeqRecord:
    '''
    
    Parameters
    ----------
    name : str
        name of the sequence you want to fetch
    database_name : stre
        name of the database u want the sequence to be fetched from
        
    Returns
    -------
    Record : Bio.SeqRecord
        biopython object with values attached to its instances. 
    
    '''
    
    # initialize
    path = '../data/csv_database/'+database_name+'.csv'
    dataframe = pd.read_csv(path)
    
    #find index of occurences of name in the dataframe and reset index
    found_the_record_df = dataframe.loc[dataframe['ID']==id].reset_index()#.index[0]
    
    # Taking data from the df
    Record = SeqRecord(Seq(str(found_the_record_df.loc[0,'seq'])))
    Record.id = int(found_the_record_df.loc[0,'ID'])
    Record.name = found_the_record_df.loc[0,'name']
    Record.description = found_the_record_df.loc[0,'description']
    Record.annotations = {'box':found_the_record_df.loc[0,'box'],'row':found_the_record_df.loc[0,'row'],'col':found_the_record_df.loc[0,'col'], }

    return Record

In [105]:
dna = get_dna_from_id(int(10019), 'primer_box1_')

In [106]:
dna

SeqRecord(seq=Seq('CAGCATTTTCAAAGGTGTG'), id=10019, name='pCYC1_F001', description='<unknown description>', dbxrefs=[])

In [12]:
# a plasmid box 
plasmid_plates = pd.read_csv('../data/csv_database/plate_MASTER.csv', index_col=False)
plasmid_box = pd.read_csv('../data/csv_database/box_MASTER.csv', index_col=False)

# a PCR fragment box
PCR_plates = pd.read_csv('../data/csv_database/plate_MASTER.csv', index_col=False)
PCR_box = pd.read_csv('../data/csv_database/box_MASTER.csv', index_col=False)

# a primer box and primer plates
primer_plates = pd.read_csv('../data/csv_database/plate_MASTER.csv', index_col=False)
primer_box = pd.read_csv('../data/csv_database/box_MASTER.csv', index_col=False)

In [72]:
# a PCR fragment box
ds_dna_plates = pd.read_csv('../data/csv_database/plate_MASTER.csv', index_col=False)
ds_dna_box = pd.read_csv('../data/csv_database/box_MASTER.csv', index_col=False)


update_database(ds_dna_plates, 'ds_dna_plates')
update_database(ds_dna_box, 'ds_dna_box')

In [13]:
update_database(plasmid_plates, 'plasmid_plates')
update_database(plasmid_box, 'plasmid_box')


update_database(PCR_plates, 'PCR_plates')
update_database(PCR_box, 'PCR_box')

update_database(primer_plates, 'primer_plates')
update_database(primer_box, 'primer_box')

In [48]:
path = '../data/Plasmids/'
files = os.listdir(path)

# get fasta files - sometimes there is a jupyter file or something here
plasmid_files_fasta =[]
plasmid_files_gb =[]

for plasmid in files:
    if plasmid.endswith('fasta'):
        plasmid_files_fasta.append(plasmid)
    if plasmid.endswith('gb'):
        plasmid_files_gb.append(plasmid)
plasmid_files = plasmid_files_fasta + plasmid_files_gb

In [51]:
len(plasmid_files)

11

In [53]:
plasmid_files

['Backbone_template - p0056_(pESC-LEU-ccdB-USER) (1).fasta',
 'gRNA2_template - pESC-LEU-gRNA_CroCPR-2 (1).fasta',
 'LEU_plasmid.fasta',
 'PL_02_E2(pRS413U-P2_PGK1-mKate2.fasta',
 'pCfB-56(pESC-LEU-gRNA_ATF1-CroCPR).fasta',
 'gRNA1_template (1).fasta',
 'pl_12_i6_pesc-ura-grna_xi2-2.gb',
 'TRP_POS_CONTROL_test.gb',
 'pRS416.gb',
 'pRS414.gb',
 'URA_POS_CONTROL_test.gb']

In [55]:

## Pandas dataframe
plasmids = []
for name in plasmid_files:
    if name.endswith('fasta'):
        for seq_record in SeqIO.parse('../data/Plasmids/'+name, format= 'fasta'):
              plasmids.append(seq_record)
    if name.endswith('gb'):
        for seq_record in SeqIO.parse('../data/Plasmids/'+name, format= 'gb'):
              plasmids.append(seq_record)

/Users/lucaslevassor/opt/anaconda3/envs/constrain/lib/python3.8/site-packages/Bio/GenBank/__init__.py:359: BiopythonParserWarning: Attempting to fix invalid location '3339..3288' as it looks like incorrect origin wrapping. Please fix input file, this could have unintended behavior.
  warnings.warn(

In [56]:
len(plasmids)

11

In [59]:
for i in range(len(plasmids)): 
    plasmids[i].name = plasmid_files[i]
plasmids

[SeqRecord(seq=Seq('TCGCGCGTTTCGGTGATGACGGTGAAAACCTCTGACACATGCAGCTCCCGGAGA...GTC'), id='seq_xRUzXWHM', name='Backbone_template - p0056_(pESC-LEU-ccdB-USER) (1).fasta', description='seq_xRUzXWHM <unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('TCGCGCGTTTCGGTGATGACGGTGAAAACCTCTGACACATGCAGCTCCCGGAGA...GTC'), id='seq_Qy1hV9Gf', name='gRNA2_template - pESC-LEU-gRNA_CroCPR-2 (1).fasta', description='seq_Qy1hV9Gf <unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('TCGCGCGTTTCGGTGATGACGGTGAAAACCTCTGACACATGCAGCTCCCGGAGA...GTC'), id='seq_Qy1hV9Gf', name='LEU_plasmid.fasta', description='seq_Qy1hV9Gf <unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('TCGCGCGTTTCGGTGATGACGGTGAAAACCTCTGACACATGCAGCTCCCGGAGA...GTC'), id='seq_stP1p5JB', name='PL_02_E2(pRS413U-P2_PGK1-mKate2.fasta', description='seq_stP1p5JB <unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('TGGCGGGTGTCGGGGCTGGCTTAACTATGCGGCATCAGAGCAGATTGTACTGAG...TGT'), id='seq_AA4vOQs1', name='pCfB-56(pESC-LEU-gRNA_ATF1-CroCPR).fasta', description='seq_AA4vOQs1 <unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('TCGCGCGTTTCGGTGATGACGGTGAAAACCTCTGACACATGCAGCTCCCGGAGA...GTC'), id='seq_Qy1hV9Gf', name='gRNA1_template (1).fasta', description='seq_Qy1hV9Gf <unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('TCGCGCGTTTCGGTGATGACGGTGAAAACCTCTGACACATGCAGCTCCCGGAGA...GTC'), id='p0054\\(pESC-URA-ccdB-USER).0', name='pl_12_i6_pesc-ura-grna_xi2-2.gb', description='', dbxrefs=[]),
 SeqRecord(seq=Seq('TCGCGCGTTTCGGTGATGACGGTGAAAACCTCTGACACATGCAGCTCCCGGAGA...GTC'), id='p0056\\(pESC-LEU-ccdB-US', name='TRP_POS_CONTROL_test.gb', description='', dbxrefs=[]),
 SeqRecord(seq=Seq('TCGCGCGTTTCGGTGATGACGGTGAAAACCTCTGACACATGCAGCTCCCGGAGA...GTC'), id='pRS416', name='pRS416.gb', description='pRS416', dbxrefs=[]),
 SeqRecord(seq=Seq('TCGCGCGTTTCGGTGATGACGGTGAAAACCTCTGACACATGCAGCTCCCGGAGA...GTC'), id='pRS414', name='pRS414.gb', description='pRS414', dbxrefs=[]),
 SeqRecord(seq=Seq('TCGCGCGTTTCGGTGATGACGGTGAAAACCTCTGACACATGCAGCTCCCGGAGA...GTC'), id='AF063849.0', name='URA_POS_CONTROL_test.gb', description='', dbxrefs=[])]

In [60]:
add_unique_ids(plasmids)
add_annotations(plasmids)

In [61]:
plasmids

[SeqRecord(seq=Seq('TCGCGCGTTTCGGTGATGACGGTGAAAACCTCTGACACATGCAGCTCCCGGAGA...GTC'), id=10000, name='Backbone_template - p0056_(pESC-LEU-ccdB-USER) (1).fasta', description='seq_xRUzXWHM <unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('TCGCGCGTTTCGGTGATGACGGTGAAAACCTCTGACACATGCAGCTCCCGGAGA...GTC'), id=10001, name='gRNA2_template - pESC-LEU-gRNA_CroCPR-2 (1).fasta', description='seq_Qy1hV9Gf <unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('TCGCGCGTTTCGGTGATGACGGTGAAAACCTCTGACACATGCAGCTCCCGGAGA...GTC'), id=10002, name='LEU_plasmid.fasta', description='seq_Qy1hV9Gf <unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('TCGCGCGTTTCGGTGATGACGGTGAAAACCTCTGACACATGCAGCTCCCGGAGA...GTC'), id=10003, name='PL_02_E2(pRS413U-P2_PGK1-mKate2.fasta', description='seq_stP1p5JB <unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('TGGCGGGTGTCGGGGCTGGCTTAACTATGCGGCATCAGAGCAGATTGTACTGAG...TGT'), id=10004, name='pCfB-56(pESC-LEU-gRNA_ATF1-CroCPR).fasta', description='seq_AA4vOQs1 <unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('TCGCGCGTTTCGGTGATGACGGTGAAAACCTCTGACACATGCAGCTCCCGGAGA...GTC'), id=10005, name='gRNA1_template (1).fasta', description='seq_Qy1hV9Gf <unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('TCGCGCGTTTCGGTGATGACGGTGAAAACCTCTGACACATGCAGCTCCCGGAGA...GTC'), id=10006, name='pl_12_i6_pesc-ura-grna_xi2-2.gb', description='', dbxrefs=[]),
 SeqRecord(seq=Seq('TCGCGCGTTTCGGTGATGACGGTGAAAACCTCTGACACATGCAGCTCCCGGAGA...GTC'), id=10007, name='TRP_POS_CONTROL_test.gb', description='', dbxrefs=[]),
 SeqRecord(seq=Seq('TCGCGCGTTTCGGTGATGACGGTGAAAACCTCTGACACATGCAGCTCCCGGAGA...GTC'), id=10008, name='pRS416.gb', description='pRS416', dbxrefs=[]),
 SeqRecord(seq=Seq('TCGCGCGTTTCGGTGATGACGGTGAAAACCTCTGACACATGCAGCTCCCGGAGA...GTC'), id=10009, name='pRS414.gb', description='pRS414', dbxrefs=[]),
 SeqRecord(seq=Seq('TCGCGCGTTTCGGTGATGACGGTGAAAACCTCTGACACATGCAGCTCCCGGAGA...GTC'), id=10010, name='URA_POS_CONTROL_test.gb', description='', dbxrefs=[])]

In [64]:
add_sequences_to_dataframe(plasmids, plasmid_plates)

In [65]:
add_sequences_to_dataframe(plasmids, plasmid_box)

In [69]:
plasmid_box

,ID,name,box,row,col,size,seq,concentration,features,location,reference,stock,comments,description,date
0,10000.0,Backbone_template - p0056_(pESC-LEU-ccdB-USER)...,0,A,1,8798.0,TCGCGCGTTTCGGTGATGACGGTGAAAACCTCTGACACATGCAGCT...,,[],NaN,,,,seq_xRUzXWHM <unknown description>,08-15-2022
1,10001.0,gRNA2_template - pESC-LEU-gRNA_CroCPR-2 (1).fasta,0,A,2,6841.0,TCGCGCGTTTCGGTGATGACGGTGAAAACCTCTGACACATGCAGCT...,,[],NaN,,,,seq_Qy1hV9Gf <unknown description>,08-15-2022
2,10002.0,LEU_plasmid.fasta,0,A,3,6841.0,TCGCGCGTTTCGGTGATGACGGTGAAAACCTCTGACACATGCAGCT...,,[],NaN,,,,seq_Qy1hV9Gf <unknown description>,08-15-2022
3,10003.0,PL_02_E2(pRS413U-P2_PGK1-mKate2.fasta,0,A,4,6982.0,TCGCGCGTTTCGGTGATGACGGTGAAAACCTCTGACACATGCAGCT...,,[],NaN,,,,seq_stP1p5JB <unknown description>,08-15-2022
4,10004.0,pCfB-56(pESC-LEU-gRNA_ATF1-CroCPR).fasta,0,A,5,7797.0,TGGCGGGTGTCGGGGCTGGCTTAACTATGCGGCATCAGAGCAGATT...,,[],NaN,,,,seq_AA4vOQs1 <unknown description>,08-15-2022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
805,NaN,NaN,9,I,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
806,NaN,NaN,9,I,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
807,NaN,NaN,9,I,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
808,NaN,NaN,9,I,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
809,NaN,NaN,9,I,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [68]:
update_database

In [70]:
update_database(plasmid_box, 'plasmid_box')

In [83]:
update_database(plasmid_plates, 'plasmid_plates')

In [73]:
path = '../data/G8H_CPR_parts/'
files = os.listdir(path)

# get fasta files - sometimes there is a jupyter file or something here
plasmid_files_fasta =[]
plasmid_files_gb =[]

for plasmid in files:
    if plasmid.endswith('fasta'):
        plasmid_files_fasta.append(plasmid)
    if plasmid.endswith('gb'):
        plasmid_files_gb.append(plasmid)
plasmid_files = plasmid_files_fasta + plasmid_files_gb

In [74]:
plasmid_files

['UP_DW_Marker.fasta',
 'CPR_tCYC1_-_2022-06-06.gb',
 'G8H_tADH1_-_2022-06-23.gb']

In [76]:

## Pandas dataframe
ds_dna = []
for name in plasmid_files:
    if name.endswith('fasta'):
        for seq_record in SeqIO.parse('../data/G8H_CPR_parts/'+name, format= 'fasta'):
              ds_dna.append(seq_record)
    if name.endswith('gb'):
        for seq_record in SeqIO.parse('../data/G8H_CPR_parts/'+name, format= 'gb'):
              ds_dna.append(seq_record)

In [77]:
ds_dna

[SeqRecord(seq=Seq('GAGGATTTTCGATGGAGCAGGATGAGGAGAAATAGTACCACATGTATATATCCA...CAA'), id='UP_XI-2', name='UP_XI-2', description='UP_XI-2 Upstream of XI-2 site', dbxrefs=[]),
 SeqRecord(seq=Seq('CACACGACTAGCGCTTTCAGATATTAAAAAGTTTAGATGTAGGTTTTAGCGGTA...CAC'), id='DW_XI-2', name='DW_XI-2', description='DW_XI-2 Downstream of XI-2 site', dbxrefs=[]),
 SeqRecord(seq=Seq('AGACGGTCACAGCTTGTCTGTAAGCGGATGCCGGGAGCAGACAAGCCCGTCAGG...ACG'), id='seq_3HMRtcpy', name='seq_3HMRtcpy', description='seq_3HMRtcpy <unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('ATGGACTCCTCATCGGAGAAGCTTTCCCCGTTCGACTTAATGACGGCAATCCTA...GAA'), id='pL_01_C7\\(pRS415-USER).0', name='AhuCPR_tCYC1', description='', dbxrefs=[]),
 SeqRecord(seq=Seq('ATGCAATCTACAACCTCCGTCAAGTTATCACCCTTTGACCTGATGACCGCATTA...GAA'), id='AanCPR_tCYC1', name='AanCPR_tCYC1', description='', dbxrefs=[]),
 SeqRecord(seq=Seq('ATGGATTCTTCTTCTGAAAAATTGTCTCCATTTGAATTGATGTCTGCTATTTTG...GAA'), id='CloCPR_tCYC1', name='CloCPR_tCYC1', description='', dbxrefs=[]),
 SeqRecord(seq=Seq('ATGCAGTCAAGTAGTGTAAAGGTGAGCACCTTCGACCTGATGAGTGCAATACTT...GAA'), id='pL_01_C7\\(pRS415-USER).0', name='CacCPR_tCYC1', description='', dbxrefs=[]),
 SeqRecord(seq=Seq('ATGGCTCAATTGGATACTTTGGATTTGGTTGTTTTGGCTGTTTTGTTGGTTGGT...GAA'), id='pL_01_C7\\(pRS415-USER).0', name='AniCPR_tCYC1', description='', dbxrefs=[]),
 SeqRecord(seq=Seq('ATGGATGAAACTGAAGCTACTTTGGGTACTCAACAAATTTCTGAAGCTTCTGAT...GAA'), id='pL_01_C7\\(pRS415-USER).0', name='CpoCPR_tCYC1', description='', dbxrefs=[]),
 SeqRecord(seq=Seq('ATGGACTCCACCTCAGAGAAGCTTTCACCGTTCGACTTCCTGACGGCAATCCTG...GAA'), id='pL_01_C7\\(pRS415-USER).0', name='OeuCPR_tCYC1', description='', dbxrefs=[]),
 SeqRecord(seq=Seq('ATGGATTCTTCTTCTGAAAAATTGTCTCCATTTGAATTGATGTCTGCTATTTTG...GAA'), id='pL_01_C7\\(pRS415-USER).0', name='RseCPR_tCYC1', description='', dbxrefs=[]),
 SeqRecord(seq=Seq('ATGACATCAGCTCTTTACGCCTCTGATCTATTTAAACAGCTGAAATCTATTATG...GAA'), id='AthATR1_tCYC1', name='AthATR1_tCYC1', description='', dbxrefs=[]),
 SeqRecord(seq=Seq('ATGGACTCATCCTCCGAGAAGTTGTCACCATTCGAACTTATGTCAGCAATTCTT...GAA'), id='CroCPR_tCYC1', name='CroCPR_tCYC1', description='', dbxrefs=[]),
 SeqRecord(seq=Seq('GAGCGACCTCATGCTATACCTGAGAAAGCAACCTGACCTACAGGAAAGAGTTAC...CAT'), id='CcalG8H_tADH1', name='CcalG8H_tADH1', description='', dbxrefs=[]),
 SeqRecord(seq=Seq('GAGCGACCTCATGCTATACCTGAGAAAGCAACCTGACCTACAGGAAAGAGTTAC...CAT'), id='pL_01_F5\\(pRS416U-mKate2-ccdB)', name='PcoG8H_tADH1', description='', dbxrefs=[]),
 SeqRecord(seq=Seq('GAGCGACCTCATGCTATACCTGAGAAAGCAACCTGACCTACAGGAAAGAGTTAC...CAT'), id='pL_01_C5\\(pRS413-USER).0', name='CroG8H_tADH1', description='', dbxrefs=[]),
 SeqRecord(seq=Seq('GAGCGACCTCATGCTATACCTGAGAAAGCAACCTGACCTACAGGAAAGAGTTAC...CAT'), id='OpumG8H_tADH1', name='OpumG8H_tADH1', description='', dbxrefs=[]),
 SeqRecord(seq=Seq('GAGCGACCTCATGCTATACCTGAGAAAGCAACCTGACCTACAGGAAAGAGTTAC...CAT'), id='CacuG8H_tADH1', name='CacuG8H_tADH1', description='', dbxrefs=[]),
 SeqRecord(seq=Seq('GAGCGACCTCATGCTATACCTGAGAAAGCAACCTGACCTACAGGAAAGAGTTAC...CAT'), id='RsepG8H_tADH1', name='RsepG8H_tADH1', description='', dbxrefs=[]),
 SeqRecord(seq=Seq('GAGCGACCTCATGCTATACCTGAGAAAGCAACCTGACCTACAGGAAAGAGTTAC...CAT'), id='SmusG8H_tADH1', name='SmusG8H_tADH1', description='', dbxrefs=[]),
 SeqRecord(seq=Seq('GAGCGACCTCATGCTATACCTGAGAAAGCAACCTGACCTACAGGAAAGAGTTAC...CAT'), id='VminG8H_tADH1', name='VminG8H_tADH1', description='', dbxrefs=[]),
 SeqRecord(seq=Seq('GAGCGACCTCATGCTATACCTGAGAAAGCAACCTGACCTACAGGAAAGAGTTAC...CAT'), id='OeuG8H_tADH1', name='OeuG8H_tADH1', description='', dbxrefs=[])]

In [79]:
add_unique_ids(ds_dna)
add_annotations(ds_dna)

In [80]:
add_sequences_to_dataframe(ds_dna, ds_dna_plates)
add_sequences_to_dataframe(ds_dna, ds_dna_box)

In [82]:
ds_dna_box

,ID,name,box,row,col,size,seq,concentration,features,location,reference,stock,comments,description,date
0,10011.0,UP_XI-2,0,A,1,569.0,GAGGATTTTCGATGGAGCAGGATGAGGAGAAATAGTACCACATGTA...,,[],NaN,,,,UP_XI-2 Upstream of XI-2 site,08-15-2022
1,10012.0,DW_XI-2,0,A,2,563.0,CACACGACTAGCGCTTTCAGATATTAAAAAGTTTAGATGTAGGTTT...,,[],NaN,,,,DW_XI-2 Downstream of XI-2 site,08-15-2022
2,10013.0,seq_3HMRtcpy,0,A,3,1415.0,AGACGGTCACAGCTTGTCTGTAAGCGGATGCCGGGAGCAGACAAGC...,,[],NaN,,,,seq_3HMRtcpy <unknown description>,08-15-2022
3,10014.0,AhuCPR_tCYC1,0,A,4,2328.0,ATGGACTCCTCATCGGAGAAGCTTTCCCCGTTCGACTTAATGACGG...,,"[SeqFeature(FeatureLocation(ExactPosition(0), ...",NaN,,,,,08-15-2022
4,10015.0,AanCPR_tCYC1,0,A,5,2298.0,ATGCAATCTACAACCTCCGTCAAGTTATCACCCTTTGACCTGATGA...,,"[SeqFeature(FeatureLocation(ExactPosition(0), ...",NaN,,,,,08-15-2022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
805,NaN,NaN,9,I,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
806,NaN,NaN,9,I,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
807,NaN,NaN,9,I,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
808,NaN,NaN,9,I,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
809,NaN,NaN,9,I,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [84]:
update_database(ds_dna_plates, 'ds_dna_plates')
update_database(ds_dna_box, 'ds_dna_box')

In [85]:
path = '../data/promoter_gb_files/'
files = os.listdir(path)

# get fasta files - sometimes there is a jupyter file or something here
plasmid_files_fasta =[]
plasmid_files_gb =[]

for plasmid in files:
    if plasmid.endswith('fasta'):
        plasmid_files_fasta.append(plasmid)
    if plasmid.endswith('gb'):
        plasmid_files_gb.append(plasmid)
plasmid_files = plasmid_files_fasta + plasmid_files_gb


## Pandas dataframe
ds_dna = []
for name in plasmid_files:
    if name.endswith('fasta'):
        for seq_record in SeqIO.parse('../data/promoter_gb_files/'+name, format= 'fasta'):
              ds_dna.append(seq_record)
    if name.endswith('gb'):
        for seq_record in SeqIO.parse('../data/promoter_gb_files/'+name, format= 'gb'):
              ds_dna.append(seq_record)

In [86]:
ds_dna

[SeqRecord(seq=Seq('CAGCATTTTCAAAGGTGTGTTCTTCGTCAGACATGTTTTAGTGTGTGAATGAAA...ATA'), id='seq_DPrPIMvy', name='pCYC1', description='', dbxrefs=[]),
 SeqRecord(seq=Seq('AATCCTACTCTTGCCGTTGCCATCCAAAATGAGCTAGAAGGTGGATTAACAAAT...ATA'), id='seq_8wWqUcpf', name='pENO2', description='', dbxrefs=[]),
 SeqRecord(seq=Seq('CACATGTCGACGAGTTTGTCATCGAATCCGTAATGAAGGCGCAAGAAAAACTAG...AAC'), id='seq_Bs85fGcK', name='pPCK1', description='', dbxrefs=[]),
 SeqRecord(seq=Seq('GTACTGCTGGCCATTTTTATTCAGGTTATTTGCGATTAGGTTGGGGTTTGTGTT...GCA'), id='seq_NFnLfXI8', name='pRPL15B', description='', dbxrefs=[]),
 SeqRecord(seq=Seq('AAAGAAACTTAATACGTTATGCCGTAATGAAGGGCTACCAAAAACGATAATCTC...ATA'), id='seq_KLllyItE', name='pCCW12', description='', dbxrefs=[]),
 SeqRecord(seq=Seq('TTTAATCTTTAGGGAGGGTAAAGTTGGATTCATCAATTTGATGAAATCCGTGTA...AAA'), id='seq_oMyQ3Qgm', name='pMLS1', description='', dbxrefs=[]),
 SeqRecord(seq=Seq('AAGGATGAGCCAAGAATAAGGGAACAAGATTTTGGTAATTTCCAAAAAATCAAT...AAA'), id='seq_Au475lsO', name='pTPI1', description='', dbxrefs=[]),
 SeqRecord(seq=Seq('CAAGCTGAACTCGCTGAAATTGAAAGAAAACTGGCAGAATCGTCTTCTGAAGAC...CAA'), id='seq_y4NqOW17', name='pURE2', description='', dbxrefs=[])]

In [87]:
add_unique_ids(ds_dna)

In [88]:
add_annotations(ds_dna)

In [89]:
add_sequences_to_dataframe(ds_dna, ds_dna_plates)
add_sequences_to_dataframe(ds_dna, ds_dna_box)

In [93]:
update_database(ds_dna_plates, 'ds_dna_plates')
update_database(ds_dna_box, 'ds_dna_box')

In [96]:
primers_teselagen = pd.read_excel('../data/G8H_CPR_library.xls', sheet_name = 'all primers')

In [97]:
primers_teselagen

,Id,Name,Target Parts,Size,Cost,Tm,Tm (3' only),Sequence (3' only),Sequence,Location
0,3460,PR_UP_tADH1_05,XI-2_UP,22,2.2,58.178,58.178,GAGGATTTTCGATGGAGC,GAGGATTTTCGATGGAGC,o2_I06
1,3461,PR_UP_tADH1_06,XI-2_UP,64,6.4,69.335,57.264,TTGTGGAAGTTCATGGC,TAGGTCAGGTTGCTTTCTCAGGTATAGCATGAGGTCGCTCTTGTGG...,o2_I07
2,3407,PR_G8H_01,"VminG8H_tADH1,SmusG8H_tADH1,RsepG8H_tADH1,Cacu...",19,1.9,57.335,57.335,GAGCGACCTCATGCTATAC,GAGCGACCTCATGCTATAC,op4_A10
3,3408,PR_G8H_02,"VminG8H_tADH1,TIS_AAAACA",62,6.2,63.653,57.979,ATGGATTACTTGACGATCGC,AGACACACAAACACAAATACACACACTAAATTAATAAAAACAATGG...,op4_A01
4,3409,PR_G8H_03,"VminG8H_tADH1,TIS_AAAACA",61,6.1,64.693,57.979,ATGGATTACTTGACGATCGC,ACACCAAGCAACTAATACTATAACATACAATAATAAAAACAATGGA...,op4_B01
...,...,...,...,...,...,...,...,...,...,...
91,3370,PR_CPR_02,"CroCPR_tCYC1,RseCPR_tCYC1,OeuCPR_tCYC1,CpoCPR_...",20,2.0,56.289,56.289,TTCTCAAGCAAGGTTTTCAG,TTCTCAAGCAAGGTTTTCAG,op4_B10
92,3468,PR_TRP1-DW_01,TRP1-marker,61,6.1,72.322,66.788,AGACGGTCACAGCTTGTCTGTAAGC,CGCATGTAACATTATACTGAAAACCTTGCTTGAGAAAGACGGTCAC...,op4_C10
93,3469,PR_TRP1-DW_02,TRP1-marker,18,1.8,65.423,65.423,CGTAGTGGGCCATCGCCC,CGTAGTGGGCCATCGCCC,op4_D10
94,3470,PR_TRP1-DW_05,XI-2_DW,63,6.3,66.938,58.341,CACACGACTAGCGCT,GCGAAAAACCGTCTATCAGGGCGATGGCCCACTACGCACACGACTA...,o2_I08
95,3471,PR_TRP1-DW_06,XI-2_DW,18,1.8,59.312,59.312,GTGGGAAGATTCCGCT,GTGGGAAGATTCCGCT,o2_I09

In [101]:
primers_tessa = []

for index, row in primers_teselagen.iterrows():
    record = SeqRecord(Seq(row['Sequence']), name = row['Name']+'_'+str(row['Id']), description = 'Anneals to '+str(row['Target Parts']))
    primers_tessa.append(record)
primers_tessa

[SeqRecord(seq=Seq('GAGGATTTTCGATGGAGC'), id='<unknown id>', name='PR_UP_tADH1_05_3460', description='Anneals to XI-2_UP', dbxrefs=[]),
 SeqRecord(seq=Seq('TAGGTCAGGTTGCTTTCTCAGGTATAGCATGAGGTCGCTCTTGTGGAAGTTCATGGC'), id='<unknown id>', name='PR_UP_tADH1_06_3461', description='Anneals to XI-2_UP', dbxrefs=[]),
 SeqRecord(seq=Seq('GAGCGACCTCATGCTATAC'), id='<unknown id>', name='PR_G8H_01_3407', description='Anneals to VminG8H_tADH1,SmusG8H_tADH1,RsepG8H_tADH1,CacuG8H_tADH1,OpumG8H_tADH1,CroG8H_tADH1,PcoG8H_tADH1,OeuG8H_tADH1,CcalG8H_tADH1', dbxrefs=[]),
 SeqRecord(seq=Seq('AGACACACAAACACAAATACACACACTAAATTAATAAAAACAATGGATTACTTG...CGC'), id='<unknown id>', name='PR_G8H_02_3408', description='Anneals to VminG8H_tADH1,TIS_AAAACA', dbxrefs=[]),
 SeqRecord(seq=Seq('ACACCAAGCAACTAATACTATAACATACAATAATAAAAACAATGGATTACTTGA...CGC'), id='<unknown id>', name='PR_G8H_03_3409', description='Anneals to VminG8H_tADH1,TIS_AAAACA', dbxrefs=[]),
 SeqRecord(seq=Seq('CGCAACTAATTATTCCATAATAAAATAACAACAAAACAATGGATTACTTGACGATCGC'), id='<unknown id>', name='PR_G8H_04_3410', description='Anneals to VminG8H_tADH1,TIS_AAAACA', dbxrefs=[]),
 SeqRecord(seq=Seq('GACAGTCACAAATTACCTACCACACAAGCAAAAACAATGGATTACTTGACGATCGC'), id='<unknown id>', name='PR_G8H_05_3411', description='Anneals to VminG8H_tADH1,TIS_AAAACA', dbxrefs=[]),
 SeqRecord(seq=Seq('AGACACACAAACACAAATACACACACTAAATTAATAAAAACAATGGACTTTGAC...ACC'), id='<unknown id>', name='PR_G8H_06_3412', description='Anneals to SmusG8H_tADH1,TIS_AAAACA', dbxrefs=[]),
 SeqRecord(seq=Seq('ACACCAAGCAACTAATACTATAACATACAATAATAAAAACAATGGACTTTGACT...ACC'), id='<unknown id>', name='PR_G8H_07_3413', description='Anneals to SmusG8H_tADH1,TIS_AAAACA', dbxrefs=[]),
 SeqRecord(seq=Seq('CGCAACTAATTATTCCATAATAAAATAACAACAAAACAATGGACTTTGACTTCTTGACC'), id='<unknown id>', name='PR_G8H_08_3414', description='Anneals to SmusG8H_tADH1,TIS_AAAACA', dbxrefs=[]),
 SeqRecord(seq=Seq('GACAGTCACAAATTACCTACCACACAAGCAAAAACAATGGACTTTGACTTCTTGACC'), id='<unknown id>', name='PR_G8H_09_3415', description='Anneals to SmusG8H_tADH1,TIS_AAAACA', dbxrefs=[]),
 SeqRecord(seq=Seq('AGACACACAAACACAAATACACACACTAAATTAATAAAAACAATGGATTACTTG...CGC'), id='<unknown id>', name='PR_G8H_10_3416', description='Anneals to RsepG8H_tADH1,TIS_AAAACA', dbxrefs=[]),
 SeqRecord(seq=Seq('ACACCAAGCAACTAATACTATAACATACAATAATAAAAACAATGGATTACTTGA...CGC'), id='<unknown id>', name='PR_G8H_11_3417', description='Anneals to RsepG8H_tADH1,TIS_AAAACA', dbxrefs=[]),
 SeqRecord(seq=Seq('CGCAACTAATTATTCCATAATAAAATAACAACAAAACAATGGATTACTTGACTATCACGC'), id='<unknown id>', name='PR_G8H_12_3418', description='Anneals to RsepG8H_tADH1,TIS_AAAACA', dbxrefs=[]),
 SeqRecord(seq=Seq('GACAGTCACAAATTACCTACCACACAAGCAAAAACAATGGATTACTTGACTATCACGC'), id='<unknown id>', name='PR_G8H_13_3419', description='Anneals to RsepG8H_tADH1,TIS_AAAACA', dbxrefs=[]),
 SeqRecord(seq=Seq('AGACACACAAACACAAATACACACACTAAATTAATAAAAACAATGGACATAATG...TCC'), id='<unknown id>', name='PR_G8H_14_3420', description='Anneals to CacuG8H_tADH1,TIS_AAAACA', dbxrefs=[]),
 SeqRecord(seq=Seq('ACACCAAGCAACTAATACTATAACATACAATAATAAAAACAATGGACATAATGG...TCC'), id='<unknown id>', name='PR_G8H_15_3421', description='Anneals to CacuG8H_tADH1,TIS_AAAACA', dbxrefs=[]),
 SeqRecord(seq=Seq('CGCAACTAATTATTCCATAATAAAATAACAACAAAACAATGGACATAATGGACT...TCC'), id='<unknown id>', name='PR_G8H_16_3422', description='Anneals to CacuG8H_tADH1,TIS_AAAACA', dbxrefs=[]),
 SeqRecord(seq=Seq('GACAGTCACAAATTACCTACCACACAAGCAAAAACAATGGACATAATGGACTTTATGTCC'), id='<unknown id>', name='PR_G8H_17_3423', description='Anneals to CacuG8H_tADH1,TIS_AAAACA', dbxrefs=[]),
 SeqRecord(seq=Seq('AGACACACAAACACAAATACACACACTAAATTAATAAAAACAATGCGTATCTTA...AAG'), id='<unknown id>', name='PR_G8H_18_3424', description='Anneals to OpumG8H_tADH1,TIS_AAAACA', dbxrefs=[]),
 SeqRecord(seq=Seq('ACACCAAGCAACTAATACTATAACATACAATAATAAAAACAATGCGTATCTTAG...AAG'), id='<unknown id>', name='PR_G8H_19_3425', description='Anneals to OpumG8H_tADH1,TIS_AAAACA', dbxrefs=[]),
 SeqRecord(seq=Seq('CGCAACTAATTATTCCATAATAAAATAACAACAAAACAATGCGTATCTTAGATTCAGAAG'), id='<unknown id>', name='PR_G8H_20_3426', description='Anneals to OpumG8H_tADH1,TIS_AAAACA', dbxrefs=[]),
 SeqRecord(seq=Seq('GACAGTCACAAATTACCTACCACACAAGCAAAAACAATGCGTATCTTAGATTCAGAAG'), id='<unknown id>', name='PR_G8H_21_3427', description='Anneals to OpumG8H_tADH1,TIS_AAAACA', dbxrefs=[]),
 SeqRecord(seq=Seq('AGACACACAAACACAAATACACACACTAAATTAATAAAAACAATGGATTACCTT...AAC'), id='<unknown id>', name='PR_G8H_22_3428', description='Anneals to CroG8H_tADH1,TIS_AAAACA', dbxrefs=[]),
 SeqRecord(seq=Seq('ACACCAAGCAACTAATACTATAACATACAATAATAAAAACAATGGATTACCTTA...AAC'), id='<unknown id>', name='PR_G8H_23_3429', description='Anneals to CroG8H_tADH1,TIS_AAAACA', dbxrefs=[]),
 SeqRecord(seq=Seq('CGCAACTAATTATTCCATAATAAAATAACAACAAAACAATGGATTACCTTACAA...AAC'), id='<unknown id>', name='PR_G8H_24_3430', description='Anneals to CroG8H_tADH1,TIS_AAAACA', dbxrefs=[]),
 SeqRecord(seq=Seq('GACAGTCACAAATTACCTACCACACAAGCAAAAACAATGGATTACCTTACAATT...AAC'), id='<unknown id>', name='PR_G8H_25_3431', description='Anneals to CroG8H_tADH1,TIS_AAAACA', dbxrefs=[]),
 SeqRecord(seq=Seq('AGACACACAAACACAAATACACACACTAAATTAATAAAAACAATGTTGGTTGAAGCTGCT'), id='<unknown id>', name='PR_G8H_26_3432', description='Anneals to PcoG8H_tADH1,TIS_AAAACA', dbxrefs=[]),
 SeqRecord(seq=Seq('ACACCAAGCAACTAATACTATAACATACAATAATAAAAACAATGTTGGTTGAAGCTGCT'), id='<unknown id>', name='PR_G8H_27_3433', description='Anneals to PcoG8H_tADH1,TIS_AAAACA', dbxrefs=[]),
 SeqRecord(seq=Seq('CGCAACTAATTATTCCATAATAAAATAACAACAAAACAATGTTGGTTGAAGCTGCT'), id='<unknown id>', name='PR_G8H_28_3434', description='Anneals to PcoG8H_tADH1,TIS_AAAACA', dbxrefs=[]),
 SeqRecord(seq=Seq('GACAGTCACAAATTACCTACCACACAAGCAAAAACAATGTTGGTTGAAGCTGCT'), id='<unknown id>', name='PR_G8H_29_3435', description='Anneals to PcoG8H_tADH1,TIS_AAAACA', dbxrefs=[]),
 SeqRecord(seq=Seq('AGACACACAAACACAAATACACACACTAAATTAATAAAAACAATGGACTTCTTA...TAG'), id='<unknown id>', name='PR_G8H_30_3436', description='Anneals to OeuG8H_tADH1,TIS_AAAACA', dbxrefs=[]),
 SeqRecord(seq=Seq('ACACCAAGCAACTAATACTATAACATACAATAATAAAAACAATGGACTTCTTAA...TAG'), id='<unknown id>', name='PR_G8H_31_3437', description='Anneals to OeuG8H_tADH1,TIS_AAAACA', dbxrefs=[]),
 SeqRecord(seq=Seq('CGCAACTAATTATTCCATAATAAAATAACAACAAAACAATGGACTTCTTAACAA...TAG'), id='<unknown id>', name='PR_G8H_32_3438', description='Anneals to OeuG8H_tADH1,TIS_AAAACA', dbxrefs=[]),
 SeqRecord(seq=Seq('GACAGTCACAAATTACCTACCACACAAGCAAAAACAATGGACTTCTTAACAATC...TAG'), id='<unknown id>', name='PR_G8H_33_3439', description='Anneals to OeuG8H_tADH1,TIS_AAAACA', dbxrefs=[]),
 SeqRecord(seq=Seq('AGACACACAAACACAAATACACACACTAAATTAATAAAAACAATGGATTACTTA...TGG'), id='<unknown id>', name='PR_G8H_34_3440', description='Anneals to CcalG8H_tADH1,TIS_AAAACA', dbxrefs=[]),
 SeqRecord(seq=Seq('ACACCAAGCAACTAATACTATAACATACAATAATAAAAACAATGGATTACTTAA...TGG'), id='<unknown id>', name='PR_G8H_35_3441', description='Anneals to CcalG8H_tADH1,TIS_AAAACA', dbxrefs=[]),
 SeqRecord(seq=Seq('CGCAACTAATTATTCCATAATAAAATAACAACAAAACAATGGATTACTTAACTA...TGG'), id='<unknown id>', name='PR_G8H_36_3442', description='Anneals to CcalG8H_tADH1,TIS_AAAACA', dbxrefs=[]),
 SeqRecord(seq=Seq('GACAGTCACAAATTACCTACCACACAAGCAAAAACAATGGATTACTTAACTATT...TGG'), id='<unknown id>', name='PR_G8H_37_3443', description='Anneals to CcalG8H_tADH1,TIS_AAAACA', dbxrefs=[]),
 SeqRecord(seq=Seq('TGTTTTTATTAATTTAGTGTGTGTATTTGTGTTTG'), id='<unknown id>', name='PR_PRO_01_3444', description='Anneals to TIS_AAAACA,pCYC1', dbxrefs=[]),
 SeqRecord(seq=Seq('AGACAGGTCCATACGCCGAGCATGCCCATTCGATAAGGCACAGCATTTTCAAAGGTGTG'), id='<unknown id>', name='PR_PRO_02_3445', description='Anneals to pCYC1,ATF-1 gRNA + TGG (39 bp)', dbxrefs=[]),
 SeqRecord(seq=Seq('TGTTTTTATTATTGTATGTTATAGTATTAGTTGCTTGG'), id='<unknown id>', name='PR_PRO_11_3454', description='Anneals to TIS_AAAACA,pENO2', dbxrefs=[]),
 SeqRecord(seq=Seq('AGACAGGTCCATACGCCGAGCATGCCCATTCGATAAGGCAAATCCTACTCTTGCCGTTG'), id='<unknown id>', name='PR_PRO_12_3455', description='Anneals to pENO2,ATF-1 gRNA + TGG (39 bp)', dbxrefs=[]),
 SeqRecord(seq=Seq('TGTTTTGTTGTTATTTTATTATGGAATAATTAGTTGC'), id='<unknown id>', name='PR_PRO_13_3456', description='Anneals to TIS_AAAACA,pPCK1', dbxrefs=[]),
 SeqRecord(seq=Seq('AGACAGGTCCATACGCCGAGCATGCCCATTCGATAAGGCACACATGTCGACGAGTTTG'), id='<unknown id>', name='PR_PRO_14_3457', description='Anneals to pPCK1,ATF-1 gRNA + TGG (39 bp)', dbxrefs=[]),
 SeqRecord(seq=Seq('TGTTTTTGCTTGTGTGGTAGGTAA'), id='<unknown id>', name='PR_PRO_15_3458', description='Anneals to TIS_AAAACA,pRPL15B', dbxrefs=[]),
 SeqRecord(seq=Seq('AGACAGGTCCATACGCCGAGCATGCCCATTCGATAAGGCAGTACTGCTGGCCATTTT'), id='<unknown id>', name='PR_PRO_16_3459', description='Anneals to pRPL15B,ATF-1 gRNA + TGG (39 bp)', dbxrefs=[]),
 SeqRecord(seq=Seq('TTATCGAATGGGCATGCTCGGCGTATGGACCTGTCTAAAGAAACTTAATACGTTATGCCG'), id='<unknown id>', name='PR_PRO_03_3446', description='Anneals to pCCW12', dbxrefs=[]),
 SeqRecord(seq=Seq('TGTTTTATATTGATATAGTGTTTAAGCGAATGAC'), id='<unknown id>', name='PR_PRO_04_3447', description='Anneals to pCCW12,TIS_AAAACA', dbxrefs=[]),
 SeqRecord(seq=Seq('TTATCGAATGGGCATGCTCGGCGTATGGACCTGTCTTTTAATCTTTAGGGAGGG...TTG'), id='<unknown id>', name='PR_PRO_05_3448', description='Anneals to pMLS1', dbxrefs=[]),
 SeqRecord(seq=Seq('TGTTTTATTTCTTAATTCTTTTATGTGCTTTTAC'), id='<unknown id>', name='PR_PRO_06_3449', description='Anneals to pMLS1,TIS_AAAACA', dbxrefs=[]),
 SeqRecord(seq=Seq('TTATCGAATGGGCATGCTCGGCGTATGGACCTGTCTAAGGATGAGCCAAGAATAAGG'), id='<unknown id>', name='PR_PRO_07_3450', description='Anneals to pTPI1', dbxrefs=[]),
 SeqRecord(seq=Seq('TGTTTTATTTTAGTTTATGTATGTGTTTTTTGTAG'), id='<unknown id>', name='PR_PRO_08_3451', description='Anneals to pTPI1,TIS_AAAACA', dbxrefs=[]),
 SeqRecord(seq=Seq('TTATCGAATGGGCATGCTCGGCGTATGGACCTGTCTCAAGCTGAACTCGCTGAA'), id='<unknown id>', name='PR_PRO_09_3452', description='Anneals to pURE2', dbxrefs=[]),
 SeqRecord(seq=Seq('TGTTTTTTGGTGTAGAACTTAATTTGCAG'), id='<unknown id>', name='PR_PRO_10_3453', description='Anneals to pURE2,TIS_AAAACA', dbxrefs=[]),
 SeqRecord(seq=Seq('GTTTTAAGCTGCAAATTAAGTTCTACACCAAAAAACAATGGACTCATCCTCCGAG'), id='<unknown id>', name='PR_CPR_01_3369', description='Anneals to TIS_AAAACA,CroCPR_tCYC1', dbxrefs=[]),
 SeqRecord(seq=Seq('ACTACAAAAAACACATACATAAACTAAAATAAAACAATGGACTCATCCTCCGAG'), id='<unknown id>', name='PR_CPR_12_3380', description='Anneals to TIS_AAAACA,CroCPR_tCYC1', dbxrefs=[]),
 SeqRecord(seq=Seq('CAAAGTAGTAAAAGCACATAAAAGAATTAAGAAATAAAACAATGGACTCATCCTCCGAG'), id='<unknown id>', name='PR_CPR_21_3389', description='Anneals to TIS_AAAACA,CroCPR_tCYC1', dbxrefs=[]),
 SeqRecord(seq=Seq('CTGTCATTCGCTTAAACACTATATCAATATAAAACAATGGACTCATCCTCCGAG'), id='<unknown id>', name='PR_CPR_30_3398', description='Anneals to TIS_AAAACA,CroCPR_tCYC1', dbxrefs=[]),
 SeqRecord(seq=Seq('GTTTTAAGCTGCAAATTAAGTTCTACACCAAAAAACAATGCAATCTACAACCTCCG'), id='<unknown id>', name='PR_CPR_11_3379', description='Anneals to TIS_AAAACA,AanCPR_tCYC1', dbxrefs=[]),
 SeqRecord(seq=Seq('ACTACAAAAAACACATACATAAACTAAAATAAAACAATGCAATCTACAACCTCCG'), id='<unknown id>', name='PR_CPR_20_3388', description='Anneals to TIS_AAAACA,AanCPR_tCYC1', dbxrefs=[]),
 SeqRecord(seq=Seq('CAAAGTAGTAAAAGCACATAAAAGAATTAAGAAATAAAACAATGCAATCTACAACCTCCG'), id='<unknown id>', name='PR_CPR_29_3397', description='Anneals to TIS_AAAACA,AanCPR_tCYC1', dbxrefs=[]),
 SeqRecord(seq=Seq('CTGTCATTCGCTTAAACACTATATCAATATAAAACAATGCAATCTACAACCTCCG'), id='<unknown id>', name='PR_CPR_38_3406', description='Anneals to TIS_AAAACA,AanCPR_tCYC1', dbxrefs=[]),
 SeqRecord(seq=Seq('GTTTTAAGCTGCAAATTAAGTTCTACACCAAAAAACAATGACATCAGCTCTTTACGC'), id='<unknown id>', name='PR_CPR_04_3372', description='Anneals to TIS_AAAACA,AthATR1_tCYC1', dbxrefs=[]),
 SeqRecord(seq=Seq('ACTACAAAAAACACATACATAAACTAAAATAAAACAATGACATCAGCTCTTTACGC'), id='<unknown id>', name='PR_CPR_14_3382', description='Anneals to TIS_AAAACA,AthATR1_tCYC1', dbxrefs=[]),
 SeqRecord(seq=Seq('CAAAGTAGTAAAAGCACATAAAAGAATTAAGAAATAAAACAATGACATCAGCTC...CGC'), id='<unknown id>', name='PR_CPR_23_3391', description='Anneals to TIS_AAAACA,AthATR1_tCYC1', dbxrefs=[]),
 SeqRecord(seq=Seq('CTGTCATTCGCTTAAACACTATATCAATATAAAACAATGACATCAGCTCTTTACGC'), id='<unknown id>', name='PR_CPR_32_3400', description='Anneals to TIS_AAAACA,AthATR1_tCYC1', dbxrefs=[]),
 SeqRecord(seq=Seq('GTTTTAAGCTGCAAATTAAGTTCTACACCAAAAAACAATGGATTCTTCTTCTGA...GTC'), id='<unknown id>', name='PR_CPR_03_3371', description='Anneals to TIS_AAAACA,RseCPR_tCYC1,CloCPR_tCYC1', dbxrefs=[]),
 SeqRecord(seq=Seq('ACTACAAAAAACACATACATAAACTAAAATAAAACAATGGATTCTTCTTCTGAA...GTC'), id='<unknown id>', name='PR_CPR_13_3381', description='Anneals to TIS_AAAACA,RseCPR_tCYC1,CloCPR_tCYC1', dbxrefs=[]),
 SeqRecord(seq=Seq('CAAAGTAGTAAAAGCACATAAAAGAATTAAGAAATAAAACAATGGATTCTTCTT...GTC'), id='<unknown id>', name='PR_CPR_22_3390', description='Anneals to TIS_AAAACA,RseCPR_tCYC1,CloCPR_tCYC1', dbxrefs=[]),
 SeqRecord(seq=Seq('CTGTCATTCGCTTAAACACTATATCAATATAAAACAATGGATTCTTCTTCTGAA...GTC'), id='<unknown id>', name='PR_CPR_31_3399', description='Anneals to TIS_AAAACA,RseCPR_tCYC1,CloCPR_tCYC1', dbxrefs=[]),
 SeqRecord(seq=Seq('GTTTTAAGCTGCAAATTAAGTTCTACACCAAAAAACAATGGACTCCTCATCGGAGA'), id='<unknown id>', name='PR_CPR_08_3376', description='Anneals to TIS_AAAACA,AhuCPR_tCYC1', dbxrefs=[]),
 SeqRecord(seq=Seq('ACTACAAAAAACACATACATAAACTAAAATAAAACAATGGACTCCTCATCGGAGA'), id='<unknown id>', name='PR_CPR_17_3385', description='Anneals to TIS_AAAACA,AhuCPR_tCYC1', dbxrefs=[]),
 SeqRecord(seq=Seq('CAAAGTAGTAAAAGCACATAAAAGAATTAAGAAATAAAACAATGGACTCCTCATCGGAGA'), id='<unknown id>', name='PR_CPR_26_3394', description='Anneals to TIS_AAAACA,AhuCPR_tCYC1', dbxrefs=[]),
 SeqRecord(seq=Seq('CTGTCATTCGCTTAAACACTATATCAATATAAAACAATGGACTCCTCATCGGAGA'), id='<unknown id>', name='PR_CPR_35_3403', description='Anneals to TIS_AAAACA,AhuCPR_tCYC1', dbxrefs=[]),
 SeqRecord(seq=Seq('GTTTTAAGCTGCAAATTAAGTTCTACACCAAAAAACAATGGCTCAATTGGATACTTTGG'), id='<unknown id>', name='PR_CPR_09_3377', description='Anneals to TIS_AAAACA,AniCPR_tCYC1', dbxrefs=[]),
 SeqRecord(seq=Seq('ACTACAAAAAACACATACATAAACTAAAATAAAACAATGGCTCAATTGGATACTTTGG'), id='<unknown id>', name='PR_CPR_18_3386', description='Anneals to TIS_AAAACA,AniCPR_tCYC1', dbxrefs=[]),
 SeqRecord(seq=Seq('CAAAGTAGTAAAAGCACATAAAAGAATTAAGAAATAAAACAATGGCTCAATTGG...TGG'), id='<unknown id>', name='PR_CPR_27_3395', description='Anneals to TIS_AAAACA,AniCPR_tCYC1', dbxrefs=[]),
 SeqRecord(seq=Seq('CTGTCATTCGCTTAAACACTATATCAATATAAAACAATGGCTCAATTGGATACTTTGG'), id='<unknown id>', name='PR_CPR_36_3404', description='Anneals to TIS_AAAACA,AniCPR_tCYC1', dbxrefs=[]),
 SeqRecord(seq=Seq('GTTTTAAGCTGCAAATTAAGTTCTACACCAAAAAACAATGCAGTCAAGTAGTGTAAAGG'), id='<unknown id>', name='PR_CPR_10_3378', description='Anneals to TIS_AAAACA,CacCPR_tCYC1', dbxrefs=[]),
 SeqRecord(seq=Seq('ACTACAAAAAACACATACATAAACTAAAATAAAACAATGCAGTCAAGTAGTGTAAAGG'), id='<unknown id>', name='PR_CPR_19_3387', description='Anneals to TIS_AAAACA,CacCPR_tCYC1', dbxrefs=[]),
 SeqRecord(seq=Seq('CAAAGTAGTAAAAGCACATAAAAGAATTAAGAAATAAAACAATGCAGTCAAGTA...AGG'), id='<unknown id>', name='PR_CPR_28_3396', description='Anneals to TIS_AAAACA,CacCPR_tCYC1', dbxrefs=[]),
 SeqRecord(seq=Seq('CTGTCATTCGCTTAAACACTATATCAATATAAAACAATGCAGTCAAGTAGTGTAAAGG'), id='<unknown id>', name='PR_CPR_37_3405', description='Anneals to TIS_AAAACA,CacCPR_tCYC1', dbxrefs=[]),
 SeqRecord(seq=Seq('GTTTTAAGCTGCAAATTAAGTTCTACACCAAAAAACAATGGACTCCACCTCAGAG'), id='<unknown id>', name='PR_CPR_06_3374', description='Anneals to TIS_AAAACA,OeuCPR_tCYC1', dbxrefs=[]),
 SeqRecord(seq=Seq('ACTACAAAAAACACATACATAAACTAAAATAAAACAATGGACTCCACCTCAGAG'), id='<unknown id>', name='PR_CPR_15_3383', description='Anneals to TIS_AAAACA,OeuCPR_tCYC1', dbxrefs=[]),
 SeqRecord(seq=Seq('CAAAGTAGTAAAAGCACATAAAAGAATTAAGAAATAAAACAATGGACTCCACCTCAGAG'), id='<unknown id>', name='PR_CPR_24_3392', description='Anneals to TIS_AAAACA,OeuCPR_tCYC1', dbxrefs=[]),
 SeqRecord(seq=Seq('CTGTCATTCGCTTAAACACTATATCAATATAAAACAATGGACTCCACCTCAGAG'), id='<unknown id>', name='PR_CPR_33_3401', description='Anneals to TIS_AAAACA,OeuCPR_tCYC1', dbxrefs=[]),
 SeqRecord(seq=Seq('GTTTTAAGCTGCAAATTAAGTTCTACACCAAAAAACAATGGATGAAACTGAAGCTAC'), id='<unknown id>', name='PR_CPR_07_3375', description='Anneals to TIS_AAAACA,CpoCPR_tCYC1', dbxrefs=[]),
 SeqRecord(seq=Seq('ACTACAAAAAACACATACATAAACTAAAATAAAACAATGGATGAAACTGAAGCTAC'), id='<unknown id>', name='PR_CPR_16_3384', description='Anneals to TIS_AAAACA,CpoCPR_tCYC1', dbxrefs=[]),
 SeqRecord(seq=Seq('CAAAGTAGTAAAAGCACATAAAAGAATTAAGAAATAAAACAATGGATGAAACTG...TAC'), id='<unknown id>', name='PR_CPR_25_3393', description='Anneals to TIS_AAAACA,CpoCPR_tCYC1', dbxrefs=[]),
 SeqRecord(seq=Seq('CTGTCATTCGCTTAAACACTATATCAATATAAAACAATGGATGAAACTGAAGCTAC'), id='<unknown id>', name='PR_CPR_34_3402', description='Anneals to TIS_AAAACA,CpoCPR_tCYC1', dbxrefs=[]),
 SeqRecord(seq=Seq('TTCTCAAGCAAGGTTTTCAG'), id='<unknown id>', name='PR_CPR_02_3370', description='Anneals to CroCPR_tCYC1,RseCPR_tCYC1,OeuCPR_tCYC1,CpoCPR_tCYC1,AhuCPR_tCYC1,AniCPR_tCYC1,CacCPR_tCYC1,CloCPR_tCYC1,AanCPR_tCYC1', dbxrefs=[]),
 SeqRecord(seq=Seq('CGCATGTAACATTATACTGAAAACCTTGCTTGAGAAAGACGGTCACAGCTTGTC...AGC'), id='<unknown id>', name='PR_TRP1-DW_01_3468', description='Anneals to TRP1-marker', dbxrefs=[]),
 SeqRecord(seq=Seq('CGTAGTGGGCCATCGCCC'), id='<unknown id>', name='PR_TRP1-DW_02_3469', description='Anneals to TRP1-marker', dbxrefs=[]),
 SeqRecord(seq=Seq('GCGAAAAACCGTCTATCAGGGCGATGGCCCACTACGCACACGACTAGCGCT'), id='<unknown id>', name='PR_TRP1-DW_05_3470', description='Anneals to XI-2_DW', dbxrefs=[]),
 SeqRecord(seq=Seq('GTGGGAAGATTCCGCT'), id='<unknown id>', name='PR_TRP1-DW_06_3471', description='Anneals to XI-2_DW', dbxrefs=[])]

In [ ]:
primers_tessa

In [102]:
add_unique_ids(primers_tessa)
add_annotations(primers_tessa)

In [103]:
primers_tessa

[SeqRecord(seq=Seq('GAGGATTTTCGATGGAGC'), id=10041, name='PR_UP_tADH1_05_3460', description='Anneals to XI-2_UP', dbxrefs=[]),
 SeqRecord(seq=Seq('TAGGTCAGGTTGCTTTCTCAGGTATAGCATGAGGTCGCTCTTGTGGAAGTTCATGGC'), id=10042, name='PR_UP_tADH1_06_3461', description='Anneals to XI-2_UP', dbxrefs=[]),
 SeqRecord(seq=Seq('GAGCGACCTCATGCTATAC'), id=10043, name='PR_G8H_01_3407', description='Anneals to VminG8H_tADH1,SmusG8H_tADH1,RsepG8H_tADH1,CacuG8H_tADH1,OpumG8H_tADH1,CroG8H_tADH1,PcoG8H_tADH1,OeuG8H_tADH1,CcalG8H_tADH1', dbxrefs=[]),
 SeqRecord(seq=Seq('AGACACACAAACACAAATACACACACTAAATTAATAAAAACAATGGATTACTTG...CGC'), id=10044, name='PR_G8H_02_3408', description='Anneals to VminG8H_tADH1,TIS_AAAACA', dbxrefs=[]),
 SeqRecord(seq=Seq('ACACCAAGCAACTAATACTATAACATACAATAATAAAAACAATGGATTACTTGA...CGC'), id=10045, name='PR_G8H_03_3409', description='Anneals to VminG8H_tADH1,TIS_AAAACA', dbxrefs=[]),
 SeqRecord(seq=Seq('CGCAACTAATTATTCCATAATAAAATAACAACAAAACAATGGATTACTTGACGATCGC'), id=10046, name='PR_G8H_04_3410', description='Anneals to VminG8H_tADH1,TIS_AAAACA', dbxrefs=[]),
 SeqRecord(seq=Seq('GACAGTCACAAATTACCTACCACACAAGCAAAAACAATGGATTACTTGACGATCGC'), id=10047, name='PR_G8H_05_3411', description='Anneals to VminG8H_tADH1,TIS_AAAACA', dbxrefs=[]),
 SeqRecord(seq=Seq('AGACACACAAACACAAATACACACACTAAATTAATAAAAACAATGGACTTTGAC...ACC'), id=10048, name='PR_G8H_06_3412', description='Anneals to SmusG8H_tADH1,TIS_AAAACA', dbxrefs=[]),
 SeqRecord(seq=Seq('ACACCAAGCAACTAATACTATAACATACAATAATAAAAACAATGGACTTTGACT...ACC'), id=10049, name='PR_G8H_07_3413', description='Anneals to SmusG8H_tADH1,TIS_AAAACA', dbxrefs=[]),
 SeqRecord(seq=Seq('CGCAACTAATTATTCCATAATAAAATAACAACAAAACAATGGACTTTGACTTCTTGACC'), id=10050, name='PR_G8H_08_3414', description='Anneals to SmusG8H_tADH1,TIS_AAAACA', dbxrefs=[]),
 SeqRecord(seq=Seq('GACAGTCACAAATTACCTACCACACAAGCAAAAACAATGGACTTTGACTTCTTGACC'), id=10051, name='PR_G8H_09_3415', description='Anneals to SmusG8H_tADH1,TIS_AAAACA', dbxrefs=[]),
 SeqRecord(seq=Seq('AGACACACAAACACAAATACACACACTAAATTAATAAAAACAATGGATTACTTG...CGC'), id=10052, name='PR_G8H_10_3416', description='Anneals to RsepG8H_tADH1,TIS_AAAACA', dbxrefs=[]),
 SeqRecord(seq=Seq('ACACCAAGCAACTAATACTATAACATACAATAATAAAAACAATGGATTACTTGA...CGC'), id=10053, name='PR_G8H_11_3417', description='Anneals to RsepG8H_tADH1,TIS_AAAACA', dbxrefs=[]),
 SeqRecord(seq=Seq('CGCAACTAATTATTCCATAATAAAATAACAACAAAACAATGGATTACTTGACTATCACGC'), id=10054, name='PR_G8H_12_3418', description='Anneals to RsepG8H_tADH1,TIS_AAAACA', dbxrefs=[]),
 SeqRecord(seq=Seq('GACAGTCACAAATTACCTACCACACAAGCAAAAACAATGGATTACTTGACTATCACGC'), id=10055, name='PR_G8H_13_3419', description='Anneals to RsepG8H_tADH1,TIS_AAAACA', dbxrefs=[]),
 SeqRecord(seq=Seq('AGACACACAAACACAAATACACACACTAAATTAATAAAAACAATGGACATAATG...TCC'), id=10056, name='PR_G8H_14_3420', description='Anneals to CacuG8H_tADH1,TIS_AAAACA', dbxrefs=[]),
 SeqRecord(seq=Seq('ACACCAAGCAACTAATACTATAACATACAATAATAAAAACAATGGACATAATGG...TCC'), id=10057, name='PR_G8H_15_3421', description='Anneals to CacuG8H_tADH1,TIS_AAAACA', dbxrefs=[]),
 SeqRecord(seq=Seq('CGCAACTAATTATTCCATAATAAAATAACAACAAAACAATGGACATAATGGACT...TCC'), id=10058, name='PR_G8H_16_3422', description='Anneals to CacuG8H_tADH1,TIS_AAAACA', dbxrefs=[]),
 SeqRecord(seq=Seq('GACAGTCACAAATTACCTACCACACAAGCAAAAACAATGGACATAATGGACTTTATGTCC'), id=10059, name='PR_G8H_17_3423', description='Anneals to CacuG8H_tADH1,TIS_AAAACA', dbxrefs=[]),
 SeqRecord(seq=Seq('AGACACACAAACACAAATACACACACTAAATTAATAAAAACAATGCGTATCTTA...AAG'), id=10060, name='PR_G8H_18_3424', description='Anneals to OpumG8H_tADH1,TIS_AAAACA', dbxrefs=[]),
 SeqRecord(seq=Seq('ACACCAAGCAACTAATACTATAACATACAATAATAAAAACAATGCGTATCTTAG...AAG'), id=10061, name='PR_G8H_19_3425', description='Anneals to OpumG8H_tADH1,TIS_AAAACA', dbxrefs=[]),
 SeqRecord(seq=Seq('CGCAACTAATTATTCCATAATAAAATAACAACAAAACAATGCGTATCTTAGATTCAGAAG'), id=10062, name='PR_G8H_20_3426', description='Anneals to OpumG8H_tADH1,TIS_AAAACA', dbxrefs=[]),
 SeqRecord(seq=Seq('GACAGTCACAAATTACCTACCACACAAGCAAAAACAATGCGTATCTTAGATTCAGAAG'), id=10063, name='PR_G8H_21_3427', description='Anneals to OpumG8H_tADH1,TIS_AAAACA', dbxrefs=[]),
 SeqRecord(seq=Seq('AGACACACAAACACAAATACACACACTAAATTAATAAAAACAATGGATTACCTT...AAC'), id=10064, name='PR_G8H_22_3428', description='Anneals to CroG8H_tADH1,TIS_AAAACA', dbxrefs=[]),
 SeqRecord(seq=Seq('ACACCAAGCAACTAATACTATAACATACAATAATAAAAACAATGGATTACCTTA...AAC'), id=10065, name='PR_G8H_23_3429', description='Anneals to CroG8H_tADH1,TIS_AAAACA', dbxrefs=[]),
 SeqRecord(seq=Seq('CGCAACTAATTATTCCATAATAAAATAACAACAAAACAATGGATTACCTTACAA...AAC'), id=10066, name='PR_G8H_24_3430', description='Anneals to CroG8H_tADH1,TIS_AAAACA', dbxrefs=[]),
 SeqRecord(seq=Seq('GACAGTCACAAATTACCTACCACACAAGCAAAAACAATGGATTACCTTACAATT...AAC'), id=10067, name='PR_G8H_25_3431', description='Anneals to CroG8H_tADH1,TIS_AAAACA', dbxrefs=[]),
 SeqRecord(seq=Seq('AGACACACAAACACAAATACACACACTAAATTAATAAAAACAATGTTGGTTGAAGCTGCT'), id=10068, name='PR_G8H_26_3432', description='Anneals to PcoG8H_tADH1,TIS_AAAACA', dbxrefs=[]),
 SeqRecord(seq=Seq('ACACCAAGCAACTAATACTATAACATACAATAATAAAAACAATGTTGGTTGAAGCTGCT'), id=10069, name='PR_G8H_27_3433', description='Anneals to PcoG8H_tADH1,TIS_AAAACA', dbxrefs=[]),
 SeqRecord(seq=Seq('CGCAACTAATTATTCCATAATAAAATAACAACAAAACAATGTTGGTTGAAGCTGCT'), id=10070, name='PR_G8H_28_3434', description='Anneals to PcoG8H_tADH1,TIS_AAAACA', dbxrefs=[]),
 SeqRecord(seq=Seq('GACAGTCACAAATTACCTACCACACAAGCAAAAACAATGTTGGTTGAAGCTGCT'), id=10071, name='PR_G8H_29_3435', description='Anneals to PcoG8H_tADH1,TIS_AAAACA', dbxrefs=[]),
 SeqRecord(seq=Seq('AGACACACAAACACAAATACACACACTAAATTAATAAAAACAATGGACTTCTTA...TAG'), id=10072, name='PR_G8H_30_3436', description='Anneals to OeuG8H_tADH1,TIS_AAAACA', dbxrefs=[]),
 SeqRecord(seq=Seq('ACACCAAGCAACTAATACTATAACATACAATAATAAAAACAATGGACTTCTTAA...TAG'), id=10073, name='PR_G8H_31_3437', description='Anneals to OeuG8H_tADH1,TIS_AAAACA', dbxrefs=[]),
 SeqRecord(seq=Seq('CGCAACTAATTATTCCATAATAAAATAACAACAAAACAATGGACTTCTTAACAA...TAG'), id=10074, name='PR_G8H_32_3438', description='Anneals to OeuG8H_tADH1,TIS_AAAACA', dbxrefs=[]),
 SeqRecord(seq=Seq('GACAGTCACAAATTACCTACCACACAAGCAAAAACAATGGACTTCTTAACAATC...TAG'), id=10075, name='PR_G8H_33_3439', description='Anneals to OeuG8H_tADH1,TIS_AAAACA', dbxrefs=[]),
 SeqRecord(seq=Seq('AGACACACAAACACAAATACACACACTAAATTAATAAAAACAATGGATTACTTA...TGG'), id=10076, name='PR_G8H_34_3440', description='Anneals to CcalG8H_tADH1,TIS_AAAACA', dbxrefs=[]),
 SeqRecord(seq=Seq('ACACCAAGCAACTAATACTATAACATACAATAATAAAAACAATGGATTACTTAA...TGG'), id=10077, name='PR_G8H_35_3441', description='Anneals to CcalG8H_tADH1,TIS_AAAACA', dbxrefs=[]),
 SeqRecord(seq=Seq('CGCAACTAATTATTCCATAATAAAATAACAACAAAACAATGGATTACTTAACTA...TGG'), id=10078, name='PR_G8H_36_3442', description='Anneals to CcalG8H_tADH1,TIS_AAAACA', dbxrefs=[]),
 SeqRecord(seq=Seq('GACAGTCACAAATTACCTACCACACAAGCAAAAACAATGGATTACTTAACTATT...TGG'), id=10079, name='PR_G8H_37_3443', description='Anneals to CcalG8H_tADH1,TIS_AAAACA', dbxrefs=[]),
 SeqRecord(seq=Seq('TGTTTTTATTAATTTAGTGTGTGTATTTGTGTTTG'), id=10080, name='PR_PRO_01_3444', description='Anneals to TIS_AAAACA,pCYC1', dbxrefs=[]),
 SeqRecord(seq=Seq('AGACAGGTCCATACGCCGAGCATGCCCATTCGATAAGGCACAGCATTTTCAAAGGTGTG'), id=10081, name='PR_PRO_02_3445', description='Anneals to pCYC1,ATF-1 gRNA + TGG (39 bp)', dbxrefs=[]),
 SeqRecord(seq=Seq('TGTTTTTATTATTGTATGTTATAGTATTAGTTGCTTGG'), id=10082, name='PR_PRO_11_3454', description='Anneals to TIS_AAAACA,pENO2', dbxrefs=[]),
 SeqRecord(seq=Seq('AGACAGGTCCATACGCCGAGCATGCCCATTCGATAAGGCAAATCCTACTCTTGCCGTTG'), id=10083, name='PR_PRO_12_3455', description='Anneals to pENO2,ATF-1 gRNA + TGG (39 bp)', dbxrefs=[]),
 SeqRecord(seq=Seq('TGTTTTGTTGTTATTTTATTATGGAATAATTAGTTGC'), id=10084, name='PR_PRO_13_3456', description='Anneals to TIS_AAAACA,pPCK1', dbxrefs=[]),
 SeqRecord(seq=Seq('AGACAGGTCCATACGCCGAGCATGCCCATTCGATAAGGCACACATGTCGACGAGTTTG'), id=10085, name='PR_PRO_14_3457', description='Anneals to pPCK1,ATF-1 gRNA + TGG (39 bp)', dbxrefs=[]),
 SeqRecord(seq=Seq('TGTTTTTGCTTGTGTGGTAGGTAA'), id=10086, name='PR_PRO_15_3458', description='Anneals to TIS_AAAACA,pRPL15B', dbxrefs=[]),
 SeqRecord(seq=Seq('AGACAGGTCCATACGCCGAGCATGCCCATTCGATAAGGCAGTACTGCTGGCCATTTT'), id=10087, name='PR_PRO_16_3459', description='Anneals to pRPL15B,ATF-1 gRNA + TGG (39 bp)', dbxrefs=[]),
 SeqRecord(seq=Seq('TTATCGAATGGGCATGCTCGGCGTATGGACCTGTCTAAAGAAACTTAATACGTTATGCCG'), id=10088, name='PR_PRO_03_3446', description='Anneals to pCCW12', dbxrefs=[]),
 SeqRecord(seq=Seq('TGTTTTATATTGATATAGTGTTTAAGCGAATGAC'), id=10089, name='PR_PRO_04_3447', description='Anneals to pCCW12,TIS_AAAACA', dbxrefs=[]),
 SeqRecord(seq=Seq('TTATCGAATGGGCATGCTCGGCGTATGGACCTGTCTTTTAATCTTTAGGGAGGG...TTG'), id=10090, name='PR_PRO_05_3448', description='Anneals to pMLS1', dbxrefs=[]),
 SeqRecord(seq=Seq('TGTTTTATTTCTTAATTCTTTTATGTGCTTTTAC'), id=10091, name='PR_PRO_06_3449', description='Anneals to pMLS1,TIS_AAAACA', dbxrefs=[]),
 SeqRecord(seq=Seq('TTATCGAATGGGCATGCTCGGCGTATGGACCTGTCTAAGGATGAGCCAAGAATAAGG'), id=10092, name='PR_PRO_07_3450', description='Anneals to pTPI1', dbxrefs=[]),
 SeqRecord(seq=Seq('TGTTTTATTTTAGTTTATGTATGTGTTTTTTGTAG'), id=10093, name='PR_PRO_08_3451', description='Anneals to pTPI1,TIS_AAAACA', dbxrefs=[]),
 SeqRecord(seq=Seq('TTATCGAATGGGCATGCTCGGCGTATGGACCTGTCTCAAGCTGAACTCGCTGAA'), id=10094, name='PR_PRO_09_3452', description='Anneals to pURE2', dbxrefs=[]),
 SeqRecord(seq=Seq('TGTTTTTTGGTGTAGAACTTAATTTGCAG'), id=10095, name='PR_PRO_10_3453', description='Anneals to pURE2,TIS_AAAACA', dbxrefs=[]),
 SeqRecord(seq=Seq('GTTTTAAGCTGCAAATTAAGTTCTACACCAAAAAACAATGGACTCATCCTCCGAG'), id=10096, name='PR_CPR_01_3369', description='Anneals to TIS_AAAACA,CroCPR_tCYC1', dbxrefs=[]),
 SeqRecord(seq=Seq('ACTACAAAAAACACATACATAAACTAAAATAAAACAATGGACTCATCCTCCGAG'), id=10097, name='PR_CPR_12_3380', description='Anneals to TIS_AAAACA,CroCPR_tCYC1', dbxrefs=[]),
 SeqRecord(seq=Seq('CAAAGTAGTAAAAGCACATAAAAGAATTAAGAAATAAAACAATGGACTCATCCTCCGAG'), id=10098, name='PR_CPR_21_3389', description='Anneals to TIS_AAAACA,CroCPR_tCYC1', dbxrefs=[]),
 SeqRecord(seq=Seq('CTGTCATTCGCTTAAACACTATATCAATATAAAACAATGGACTCATCCTCCGAG'), id=10099, name='PR_CPR_30_3398', description='Anneals to TIS_AAAACA,CroCPR_tCYC1', dbxrefs=[]),
 SeqRecord(seq=Seq('GTTTTAAGCTGCAAATTAAGTTCTACACCAAAAAACAATGCAATCTACAACCTCCG'), id=10100, name='PR_CPR_11_3379', description='Anneals to TIS_AAAACA,AanCPR_tCYC1', dbxrefs=[]),
 SeqRecord(seq=Seq('ACTACAAAAAACACATACATAAACTAAAATAAAACAATGCAATCTACAACCTCCG'), id=10101, name='PR_CPR_20_3388', description='Anneals to TIS_AAAACA,AanCPR_tCYC1', dbxrefs=[]),
 SeqRecord(seq=Seq('CAAAGTAGTAAAAGCACATAAAAGAATTAAGAAATAAAACAATGCAATCTACAACCTCCG'), id=10102, name='PR_CPR_29_3397', description='Anneals to TIS_AAAACA,AanCPR_tCYC1', dbxrefs=[]),
 SeqRecord(seq=Seq('CTGTCATTCGCTTAAACACTATATCAATATAAAACAATGCAATCTACAACCTCCG'), id=10103, name='PR_CPR_38_3406', description='Anneals to TIS_AAAACA,AanCPR_tCYC1', dbxrefs=[]),
 SeqRecord(seq=Seq('GTTTTAAGCTGCAAATTAAGTTCTACACCAAAAAACAATGACATCAGCTCTTTACGC'), id=10104, name='PR_CPR_04_3372', description='Anneals to TIS_AAAACA,AthATR1_tCYC1', dbxrefs=[]),
 SeqRecord(seq=Seq('ACTACAAAAAACACATACATAAACTAAAATAAAACAATGACATCAGCTCTTTACGC'), id=10105, name='PR_CPR_14_3382', description='Anneals to TIS_AAAACA,AthATR1_tCYC1', dbxrefs=[]),
 SeqRecord(seq=Seq('CAAAGTAGTAAAAGCACATAAAAGAATTAAGAAATAAAACAATGACATCAGCTC...CGC'), id=10106, name='PR_CPR_23_3391', description='Anneals to TIS_AAAACA,AthATR1_tCYC1', dbxrefs=[]),
 SeqRecord(seq=Seq('CTGTCATTCGCTTAAACACTATATCAATATAAAACAATGACATCAGCTCTTTACGC'), id=10107, name='PR_CPR_32_3400', description='Anneals to TIS_AAAACA,AthATR1_tCYC1', dbxrefs=[]),
 SeqRecord(seq=Seq('GTTTTAAGCTGCAAATTAAGTTCTACACCAAAAAACAATGGATTCTTCTTCTGA...GTC'), id=10108, name='PR_CPR_03_3371', description='Anneals to TIS_AAAACA,RseCPR_tCYC1,CloCPR_tCYC1', dbxrefs=[]),
 SeqRecord(seq=Seq('ACTACAAAAAACACATACATAAACTAAAATAAAACAATGGATTCTTCTTCTGAA...GTC'), id=10109, name='PR_CPR_13_3381', description='Anneals to TIS_AAAACA,RseCPR_tCYC1,CloCPR_tCYC1', dbxrefs=[]),
 SeqRecord(seq=Seq('CAAAGTAGTAAAAGCACATAAAAGAATTAAGAAATAAAACAATGGATTCTTCTT...GTC'), id=10110, name='PR_CPR_22_3390', description='Anneals to TIS_AAAACA,RseCPR_tCYC1,CloCPR_tCYC1', dbxrefs=[]),
 SeqRecord(seq=Seq('CTGTCATTCGCTTAAACACTATATCAATATAAAACAATGGATTCTTCTTCTGAA...GTC'), id=10111, name='PR_CPR_31_3399', description='Anneals to TIS_AAAACA,RseCPR_tCYC1,CloCPR_tCYC1', dbxrefs=[]),
 SeqRecord(seq=Seq('GTTTTAAGCTGCAAATTAAGTTCTACACCAAAAAACAATGGACTCCTCATCGGAGA'), id=10112, name='PR_CPR_08_3376', description='Anneals to TIS_AAAACA,AhuCPR_tCYC1', dbxrefs=[]),
 SeqRecord(seq=Seq('ACTACAAAAAACACATACATAAACTAAAATAAAACAATGGACTCCTCATCGGAGA'), id=10113, name='PR_CPR_17_3385', description='Anneals to TIS_AAAACA,AhuCPR_tCYC1', dbxrefs=[]),
 SeqRecord(seq=Seq('CAAAGTAGTAAAAGCACATAAAAGAATTAAGAAATAAAACAATGGACTCCTCATCGGAGA'), id=10114, name='PR_CPR_26_3394', description='Anneals to TIS_AAAACA,AhuCPR_tCYC1', dbxrefs=[]),
 SeqRecord(seq=Seq('CTGTCATTCGCTTAAACACTATATCAATATAAAACAATGGACTCCTCATCGGAGA'), id=10115, name='PR_CPR_35_3403', description='Anneals to TIS_AAAACA,AhuCPR_tCYC1', dbxrefs=[]),
 SeqRecord(seq=Seq('GTTTTAAGCTGCAAATTAAGTTCTACACCAAAAAACAATGGCTCAATTGGATACTTTGG'), id=10116, name='PR_CPR_09_3377', description='Anneals to TIS_AAAACA,AniCPR_tCYC1', dbxrefs=[]),
 SeqRecord(seq=Seq('ACTACAAAAAACACATACATAAACTAAAATAAAACAATGGCTCAATTGGATACTTTGG'), id=10117, name='PR_CPR_18_3386', description='Anneals to TIS_AAAACA,AniCPR_tCYC1', dbxrefs=[]),
 SeqRecord(seq=Seq('CAAAGTAGTAAAAGCACATAAAAGAATTAAGAAATAAAACAATGGCTCAATTGG...TGG'), id=10118, name='PR_CPR_27_3395', description='Anneals to TIS_AAAACA,AniCPR_tCYC1', dbxrefs=[]),
 SeqRecord(seq=Seq('CTGTCATTCGCTTAAACACTATATCAATATAAAACAATGGCTCAATTGGATACTTTGG'), id=10119, name='PR_CPR_36_3404', description='Anneals to TIS_AAAACA,AniCPR_tCYC1', dbxrefs=[]),
 SeqRecord(seq=Seq('GTTTTAAGCTGCAAATTAAGTTCTACACCAAAAAACAATGCAGTCAAGTAGTGTAAAGG'), id=10120, name='PR_CPR_10_3378', description='Anneals to TIS_AAAACA,CacCPR_tCYC1', dbxrefs=[]),
 SeqRecord(seq=Seq('ACTACAAAAAACACATACATAAACTAAAATAAAACAATGCAGTCAAGTAGTGTAAAGG'), id=10121, name='PR_CPR_19_3387', description='Anneals to TIS_AAAACA,CacCPR_tCYC1', dbxrefs=[]),
 SeqRecord(seq=Seq('CAAAGTAGTAAAAGCACATAAAAGAATTAAGAAATAAAACAATGCAGTCAAGTA...AGG'), id=10122, name='PR_CPR_28_3396', description='Anneals to TIS_AAAACA,CacCPR_tCYC1', dbxrefs=[]),
 SeqRecord(seq=Seq('CTGTCATTCGCTTAAACACTATATCAATATAAAACAATGCAGTCAAGTAGTGTAAAGG'), id=10123, name='PR_CPR_37_3405', description='Anneals to TIS_AAAACA,CacCPR_tCYC1', dbxrefs=[]),
 SeqRecord(seq=Seq('GTTTTAAGCTGCAAATTAAGTTCTACACCAAAAAACAATGGACTCCACCTCAGAG'), id=10124, name='PR_CPR_06_3374', description='Anneals to TIS_AAAACA,OeuCPR_tCYC1', dbxrefs=[]),
 SeqRecord(seq=Seq('ACTACAAAAAACACATACATAAACTAAAATAAAACAATGGACTCCACCTCAGAG'), id=10125, name='PR_CPR_15_3383', description='Anneals to TIS_AAAACA,OeuCPR_tCYC1', dbxrefs=[]),
 SeqRecord(seq=Seq('CAAAGTAGTAAAAGCACATAAAAGAATTAAGAAATAAAACAATGGACTCCACCTCAGAG'), id=10126, name='PR_CPR_24_3392', description='Anneals to TIS_AAAACA,OeuCPR_tCYC1', dbxrefs=[]),
 SeqRecord(seq=Seq('CTGTCATTCGCTTAAACACTATATCAATATAAAACAATGGACTCCACCTCAGAG'), id=10127, name='PR_CPR_33_3401', description='Anneals to TIS_AAAACA,OeuCPR_tCYC1', dbxrefs=[]),
 SeqRecord(seq=Seq('GTTTTAAGCTGCAAATTAAGTTCTACACCAAAAAACAATGGATGAAACTGAAGCTAC'), id=10128, name='PR_CPR_07_3375', description='Anneals to TIS_AAAACA,CpoCPR_tCYC1', dbxrefs=[]),
 SeqRecord(seq=Seq('ACTACAAAAAACACATACATAAACTAAAATAAAACAATGGATGAAACTGAAGCTAC'), id=10129, name='PR_CPR_16_3384', description='Anneals to TIS_AAAACA,CpoCPR_tCYC1', dbxrefs=[]),
 SeqRecord(seq=Seq('CAAAGTAGTAAAAGCACATAAAAGAATTAAGAAATAAAACAATGGATGAAACTG...TAC'), id=10130, name='PR_CPR_25_3393', description='Anneals to TIS_AAAACA,CpoCPR_tCYC1', dbxrefs=[]),
 SeqRecord(seq=Seq('CTGTCATTCGCTTAAACACTATATCAATATAAAACAATGGATGAAACTGAAGCTAC'), id=10131, name='PR_CPR_34_3402', description='Anneals to TIS_AAAACA,CpoCPR_tCYC1', dbxrefs=[]),
 SeqRecord(seq=Seq('TTCTCAAGCAAGGTTTTCAG'), id=10132, name='PR_CPR_02_3370', description='Anneals to CroCPR_tCYC1,RseCPR_tCYC1,OeuCPR_tCYC1,CpoCPR_tCYC1,AhuCPR_tCYC1,AniCPR_tCYC1,CacCPR_tCYC1,CloCPR_tCYC1,AanCPR_tCYC1', dbxrefs=[]),
 SeqRecord(seq=Seq('CGCATGTAACATTATACTGAAAACCTTGCTTGAGAAAGACGGTCACAGCTTGTC...AGC'), id=10133, name='PR_TRP1-DW_01_3468', description='Anneals to TRP1-marker', dbxrefs=[]),
 SeqRecord(seq=Seq('CGTAGTGGGCCATCGCCC'), id=10134, name='PR_TRP1-DW_02_3469', description='Anneals to TRP1-marker', dbxrefs=[]),
 SeqRecord(seq=Seq('GCGAAAAACCGTCTATCAGGGCGATGGCCCACTACGCACACGACTAGCGCT'), id=10135, name='PR_TRP1-DW_05_3470', description='Anneals to XI-2_DW', dbxrefs=[]),
 SeqRecord(seq=Seq('GTGGGAAGATTCCGCT'), id=10136, name='PR_TRP1-DW_06_3471', description='Anneals to XI-2_DW', dbxrefs=[])]

In [104]:
add_sequences_to_dataframe(primers_tessa, primer_plates)
add_sequences_to_dataframe(primers_tessa, primer_box)

In [108]:
primer_box['location'] = 'primer_box'
primer_box

,ID,name,box,row,col,size,seq,concentration,features,location,reference,stock,comments,description,date
0,10041.0,PR_UP_tADH1_05_3460,0,A,1,18.0,GAGGATTTTCGATGGAGC,,[],primer_box,,,,Anneals to XI-2_UP,08-15-2022
1,10042.0,PR_UP_tADH1_06_3461,0,A,2,57.0,TAGGTCAGGTTGCTTTCTCAGGTATAGCATGAGGTCGCTCTTGTGG...,,[],primer_box,,,,Anneals to XI-2_UP,08-15-2022
2,10043.0,PR_G8H_01_3407,0,A,3,19.0,GAGCGACCTCATGCTATAC,,[],primer_box,,,,"Anneals to VminG8H_tADH1,SmusG8H_tADH1,RsepG8H...",08-15-2022
3,10044.0,PR_G8H_02_3408,0,A,4,62.0,AGACACACAAACACAAATACACACACTAAATTAATAAAAACAATGG...,,[],primer_box,,,,"Anneals to VminG8H_tADH1,TIS_AAAACA",08-15-2022
4,10045.0,PR_G8H_03_3409,0,A,5,61.0,ACACCAAGCAACTAATACTATAACATACAATAATAAAAACAATGGA...,,[],primer_box,,,,"Anneals to VminG8H_tADH1,TIS_AAAACA",08-15-2022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
805,NaN,NaN,9,I,5,NaN,NaN,NaN,NaN,primer_box,NaN,NaN,NaN,NaN,NaN
806,NaN,NaN,9,I,6,NaN,NaN,NaN,NaN,primer_box,NaN,NaN,NaN,NaN,NaN
807,NaN,NaN,9,I,7,NaN,NaN,NaN,NaN,primer_box,NaN,NaN,NaN,NaN,NaN
808,NaN,NaN,9,I,8,NaN,NaN,NaN,NaN,primer_box,NaN,NaN,NaN,NaN,NaN
809,NaN,NaN,9,I,9,NaN,NaN,NaN,NaN,primer_box,NaN,NaN,NaN,NaN,NaN

In [126]:
def get_dna_from_plate_id(id:str, database_name:str)-> SeqRecord:
    '''fetch dna based on the id from the database of choice. 
    
    Parameters
    ----------
    name : str
        name of the sequence you want to fetch
    database_name : str
        name of the database u want the sequence to be fetched from
        
    Returns
    -------
    Record : Bio.SeqRecord
        biopython object with values attached to its instances. 
    
    '''
    
    # initialize
    path = '../data/csv_database/'+database_name+'.csv'
    dataframe = pd.read_csv(path)
    
    #find index of occurences of name in the dataframe and reset index
    found_the_record_df = dataframe.loc[dataframe['ID']==id].reset_index()#.index[0]
    
    # Taking data from the df
    Record = SeqRecord(Seq(str(found_the_record_df.loc[0,'seq'])))
    Record.id = int(found_the_record_df.loc[0,'ID'])
    Record.name = found_the_record_df.loc[0,'name']
    Record.description = found_the_record_df.loc[0,'description']
    Record.annotations = {'plate':found_the_record_df.loc[0,'plate'],
                        'row':found_the_record_df.loc[0,'row'],
                        'col':found_the_record_df.loc[0,'col'],
                        # adding the batches 

                        'batches': [{'location':str(found_the_record_df.loc[0,'plate'])+str(found_the_record_df.loc[0,'row'])+str(found_the_record_df.loc[0,'col']),
                                       'volume':str(found_the_record_df.loc[0,'stock']),'concentration':str(found_the_record_df.loc[0,'concentration'])}],}

    return Record

def get_dna_from_box_id(id:str, database_name:str)-> SeqRecord:
    '''fetch dna based on the id from the database of choice. 
    
    Parameters
    ----------
    name : str
        name of the sequence you want to fetch
    database_name : str
        name of the database u want the sequence to be fetched from
        
    Returns
    -------
    Record : Bio.SeqRecord
        biopython object with values attached to its instances. 
    
    '''
    
    # initialize
    path = '../data/csv_database/'+database_name+'.csv'
    dataframe = pd.read_csv(path)
    
    #find index of occurences of name in the dataframe and reset index
    found_the_record_df = dataframe.loc[dataframe['ID']==id].reset_index()#.index[0]
    
    # Taking data from the df
    Record = SeqRecord(Seq(str(found_the_record_df.loc[0,'seq'])))
    Record.id = int(found_the_record_df.loc[0,'ID'])
    Record.name = found_the_record_df.loc[0,'name']
    Record.description = found_the_record_df.loc[0,'description']
    Record.annotations = {'box':found_the_record_df.loc[0,'box'],
                        'row':found_the_record_df.loc[0,'row'],
                        'col':found_the_record_df.loc[0,'col'],
                        # adding the batches 

                        'batches': [{'location':str(found_the_record_df.loc[0,'plate'])+str(found_the_record_df.loc[0,'row'])+str(found_the_record_df.loc[0,'col']),
                                       'volume':str(found_the_record_df.loc[0,'stock']),'concentration':str(found_the_record_df.loc[0,'concentration'])}],}

    return Record

In [270]:
def get_dna_from_plate_name(name:str, database_name:str)-> SeqRecord:
    ''' fetch dna based on the name from the database of choice. 
    
    Parameters
    ----------
    name : str
        name of the sequence you want to fetch
    database_name : str
        name of the database u want the sequence to be fetched from
        
    Returns
    -------
    Record : Bio.SeqRecord
        biopython object with values attached to its instances. 
    '''
    
    # initialize
    path = '../data/csv_database/'+database_name+'.csv'
    dataframe = pd.read_csv(path)
    
    #find index of occurences of name in the dataframe and reset index
    found_the_record_df = dataframe.loc[dataframe['name']==name].reset_index()#.index[0]
    
    # Taking data from the df
    Record = SeqRecord(Seq(str(found_the_record_df.loc[0,'seq'])))
    Record.id = int(found_the_record_df.loc[0,'ID'])
    Record.name = found_the_record_df.loc[0,'name']
    Record.description = found_the_record_df.loc[0,'description']
    Record.annotations = {'plate':found_the_record_df.loc[0,'plate'],
                          'row':found_the_record_df.loc[0,'row'],
                          'col':found_the_record_df.loc[0,'col'],
                          # adding the batches 
                          'batches': [{'location':str(found_the_record_df.loc[0,'location'])+ str(found_the_record_df.loc[0,'plate'])+str(found_the_record_df.loc[0,'row'])+str(found_the_record_df.loc[0,'col']),
                                       'volume':str(found_the_record_df.loc[0,'stock']),'concentration':str(found_the_record_df.loc[0,'concentration'])}],
                         }

    return Record



def get_dna_from_box_name(name:str, database_name:str)-> SeqRecord:
    ''' fetch dna based on the name from the database of choice. 
    
    Parameters
    ----------
    name : str
        name of the sequence you want to fetch
    database_name : str
        name of the database u want the sequence to be fetched from
        
    Returns
    -------
    Record : Bio.SeqRecord
        biopython object with values attached to its instances. 
    '''
    
    # initialize
    path = '../data/csv_database/'+database_name+'.csv'
    dataframe = pd.read_csv(path)
    
    #find index of occurences of name in the dataframe and reset index
    found_the_record_df = dataframe.loc[dataframe['name']==name].reset_index()#.index[0]
    
    # Taking data from the df
    Record = SeqRecord(Seq(str(found_the_record_df.loc[0,'seq'])))
    Record.id = int(found_the_record_df.loc[0,'ID'])
    Record.name = found_the_record_df.loc[0,'name']
    Record.description = found_the_record_df.loc[0,'description']
    Record.annotations = {'box':found_the_record_df.loc[0,'box'],
                          'row':found_the_record_df.loc[0,'row'],
                          'col':found_the_record_df.loc[0,'col'],
                          # adding the batches 
                          'batches': [{'location':str(found_the_record_df.loc[0,'location'])+ str(found_the_record_df.loc[0,'box'])+str(found_the_record_df.loc[0,'row'])+str(found_the_record_df.loc[0,'col']),
                                       'volume':str(found_the_record_df.loc[0,'stock']),'concentration':str(found_the_record_df.loc[0,'concentration'])}],
                         }

    return Record

In [169]:
dna = get_dna_from_name('AhuCPR_tCYC1', 'ds_dna_plates') 
dna

SeqRecord(seq=Seq('ATGGACTCCTCATCGGAGAAGCTTTCCCCGTTCGACTTAATGACGGCAATCCTA...GAA'), id=10014, name='AhuCPR_tCYC1', description=nan, dbxrefs=[])

In [170]:
dna.annotations

{'plate': 0,
 'row': 'A',
 'col': 4,
 'batches': [{'location': '0A4', 'volume': 'nan', 'concentration': 'nan'}]}

In [172]:
update_database(primer_plates, 'primer_plates')
update_database(primer_box, 'primer_box')

In [223]:
path = '../data/primers/'
files = os.listdir(path)

# get fasta files - sometimes there is a jupyter file or something here
plasmid_files_fasta =[]
plasmid_files_gb =[]

for plasmid in files:
    if plasmid.endswith('fasta'):
        plasmid_files_fasta.append(plasmid)
    if plasmid.endswith('gb'):
        plasmid_files_gb.append(plasmid)
plasmid_files = plasmid_files_fasta + plasmid_files_gb
print(len(plasmid_files_fasta))
print(plasmid_files_fasta)
print(len(plasmid_files))
## Pandas dataframe
primers1 = []
for name in plasmid_files:
    if name.endswith('fasta'):
        for seq_record in SeqIO.parse('../data/primers/'+name, format= 'fasta'):
              primers1.append(seq_record)
    if name.endswith('gb'):
        for seq_record in SeqIO.parse('../data/primers/'+name, format= 'gb'):
              primers1.append(seq_record)
print(len(primers1))

12
['USER_XhoI_Fw.fasta', 'XI-3- down-out-sq.fasta', 'tADH1_fw.fasta', 'XI_2_sq_rv.fasta', 'XI-3- up-out-sq.fasta', 'tADH1_160_rv.fasta', 'pPGK1_Seq_Rv.fasta', 'pad_pCPR_fw.fasta', 'tCYC1_150_rv.fasta', 'XI_2_sq_fw.fasta', 'tTRP1_60_Fw.fasta', 'pad_pG8H_fw.fasta']
12
12

In [219]:

len(primers1)

12

In [224]:
plasmid_files

['USER_XhoI_Fw.fasta',
 'XI-3- down-out-sq.fasta',
 'tADH1_fw.fasta',
 'XI_2_sq_rv.fasta',
 'XI-3- up-out-sq.fasta',
 'tADH1_160_rv.fasta',
 'pPGK1_Seq_Rv.fasta',
 'pad_pCPR_fw.fasta',
 'tCYC1_150_rv.fasta',
 'XI_2_sq_fw.fasta',
 'tTRP1_60_Fw.fasta',
 'pad_pG8H_fw.fasta']

In [241]:
len(primers1)

12

In [242]:
for i in range(len(primers1)): 
    primers1[i].name = plasmid_files[i][:-6]
primers1

[SeqRecord(seq=Seq('ACTctcgagAGCGACCTCATGCTATACC'), id=10137, name='USER_XhoI_Fw', description='seq_hhGreWwa <unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('CACATTGAGCGAATGAAACG'), id=10138, name='XI-3- down-out-sq', description='seq_wjA1oNs1 <unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('GTTGACACTTCTAAATAAGCGAATTTC'), id=10139, name='tADH1_fw', description='seq_CQBEbYLQ <unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('GAGACAAGATGGGGCAAGAC'), id=10140, name='XI_2_sq_rv', description='seq_8At1dmPw <unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('GTGCTTGATTTGCGTCATTC'), id=10141, name='XI-3- up-out-sq', description='seq_OvLTlQju <unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('GAAATTCGCTTATTTAGAAGTGTC'), id=10142, name='tADH1_160_rv', description='seq_LkbJj9Ny <unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('AATTCAAGAAGGAGGGAAAC'), id=10143, name='pPGK1_Seq_Rv', description='seq_ahHIVhFv <unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('GGCGTATGGACCTGTCT'), id=10144, name='pad_pCPR_fw', description='seq_G6JFHeOC <unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('CTCCTTCCTTTTCGGTTAGAG'), id=10145, name='tCYC1_150_rv', description='seq_qMIkcI4R <unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('GTTTGTAGTTGGCGGTGGAG'), id=10146, name='XI_2_sq_fw', description='seq_f0DxM4nU <unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('ACCGCACAGATGCGTAAG'), id=10147, name='tTRP1_60_Fw', description='seq_YLTR2B9y <unknown description>', dbxrefs=[]),
 SeqRecord(seq=Seq('TGCCCATTCGATAAGGCA'), id=10148, name='pad_pG8H_fw', description='seq_mSRja9xj <unknown description>', dbxrefs=[])]

In [259]:
primer_plates = pd.read_csv( '../data/csv_database/primer_plates.csv')
primer_box = pd.read_csv( '../data/csv_database/primer_box.csv')

In [260]:
add_unique_ids(primers1)
add_annotations(primers1)

In [261]:
primers1[0].name

'USER_XhoI_Fw'

In [262]:
add_sequences_to_dataframe(primers1, primer_box, 162)
add_sequences_to_dataframe(primers1, primer_plates,162)

In [263]:
get_box(2, primer_box).head(50)

,ID,name,box,row,col,size,seq,concentration,features,location,reference,stock,comments,description,date
162,10137.0,USER_XhoI_Fw,2,A,1,28.0,ACTctcgagAGCGACCTCATGCTATACC,,[],primer_box,,,,seq_hhGreWwa <unknown description>,08-15-2022
163,10138.0,XI-3- down-out-sq,2,A,2,20.0,CACATTGAGCGAATGAAACG,,[],primer_box,,,,seq_wjA1oNs1 <unknown description>,08-15-2022
164,10139.0,tADH1_fw,2,A,3,27.0,GTTGACACTTCTAAATAAGCGAATTTC,,[],primer_box,,,,seq_CQBEbYLQ <unknown description>,08-15-2022
165,10140.0,XI_2_sq_rv,2,A,4,20.0,GAGACAAGATGGGGCAAGAC,,[],primer_box,,,,seq_8At1dmPw <unknown description>,08-15-2022
166,10141.0,XI-3- up-out-sq,2,A,5,20.0,GTGCTTGATTTGCGTCATTC,,[],primer_box,,,,seq_OvLTlQju <unknown description>,08-15-2022
167,10142.0,tADH1_160_rv,2,A,6,24.0,GAAATTCGCTTATTTAGAAGTGTC,,[],primer_box,,,,seq_LkbJj9Ny <unknown description>,08-15-2022
168,10143.0,pPGK1_Seq_Rv,2,A,7,20.0,AATTCAAGAAGGAGGGAAAC,,[],primer_box,,,,seq_ahHIVhFv <unknown description>,08-15-2022
169,10144.0,pad_pCPR_fw,2,A,8,17.0,GGCGTATGGACCTGTCT,,[],primer_box,,,,seq_G6JFHeOC <unknown description>,08-15-2022
170,10145.0,tCYC1_150_rv,2,A,9,21.0,CTCCTTCCTTTTCGGTTAGAG,,[],primer_box,,,,seq_qMIkcI4R <unknown description>,08-15-2022
171,10146.0,XI_2_sq_fw,2,B,1,20.0,GTTTGTAGTTGGCGGTGGAG,,[],primer_box,,,,seq_f0DxM4nU <unknown description>,08-15-2022
172,10147.0,tTRP1_60_Fw,2,B,2,18.0,ACCGCACAGATGCGTAAG,,[],primer_box,,,,seq_YLTR2B9y <unknown description>,08-15-2022
173,10148.0,pad_pG8H_fw,2,B,3,18.0,TGCCCATTCGATAAGGCA,,[],primer_box,,,,seq_mSRja9xj <unknown description>,08-15-2022
174,NaN,NaN,2,B,4,NaN,NaN,NaN,NaN,primer_box,NaN,NaN,NaN,NaN,NaN
175,NaN,NaN,2,B,5,NaN,NaN,NaN,NaN,primer_box,NaN,NaN,NaN,NaN,NaN
176,NaN,NaN,2,B,6,NaN,NaN,NaN,NaN,primer_box,NaN,NaN,NaN,NaN,NaN
177,NaN,NaN,2,B,7,NaN,NaN,NaN,NaN,primer_box,NaN,NaN,NaN,NaN,NaN
178,NaN,NaN,2,B,8,NaN,NaN,NaN,NaN,primer_box,NaN,NaN,NaN,NaN,NaN
179,NaN,NaN,2,B,9,NaN,NaN,NaN,NaN,primer_box,NaN,NaN,NaN,NaN,NaN
180,NaN,NaN,2,C,1,NaN,NaN,NaN,NaN,primer_box,NaN,NaN,NaN,NaN,NaN
181,NaN,NaN,2,C,2,NaN,NaN,NaN,NaN,primer_box,NaN,NaN,NaN,NaN,NaN
182,NaN,NaN,2,C,3,NaN,NaN,NaN,NaN,primer_box,NaN,NaN,NaN,NaN,NaN
183,NaN,NaN,2,C,4,NaN,NaN,NaN,NaN,primer_box,NaN,NaN,NaN,NaN,NaN
184,NaN,NaN,2,C,5,NaN,NaN,NaN,NaN,primer_box,NaN,NaN,NaN,NaN,NaN
185,NaN,NaN,2,C,6,NaN,NaN,NaN,NaN,primer_box,NaN,NaN,NaN,NaN,NaN
186,NaN,NaN,2,C,7,NaN,NaN,NaN,NaN,primer_box,NaN,NaN,NaN,NaN,NaN
187,NaN,NaN,2,C,8,NaN,NaN,NaN,NaN,primer_box,NaN,NaN,NaN,NaN,NaN
188,NaN,NaN,2,C,9,NaN,NaN,NaN,NaN,primer_box,NaN,NaN,NaN,NaN,NaN
189,NaN,NaN,2,D,1,NaN,NaN,NaN,NaN,primer_box,NaN,NaN,NaN,NaN,NaN
190,NaN,NaN,2,D,2,NaN,NaN,NaN,NaN,primer_box,NaN,NaN,NaN,NaN,NaN
191,NaN,NaN,2,D,3,NaN,NaN,NaN,NaN,primer_box,NaN,NaN,NaN,NaN,NaN
192,NaN,NaN,2,D,4,NaN,NaN,NaN,NaN,primer_box,NaN,NaN,NaN,NaN,NaN
193,NaN,NaN,2,D,5,NaN,NaN,NaN,NaN,primer_box,NaN,NaN,NaN,NaN,NaN
194,NaN,NaN,2,D,6,NaN,NaN,NaN,NaN,primer_box,NaN,NaN,NaN,NaN,NaN
195,NaN,NaN,2,D,7,NaN,NaN,NaN,NaN,primer_box,NaN,NaN,NaN,NaN,NaN
196,NaN,NaN,2,D,8,NaN,NaN,NaN,NaN,primer_box,NaN,NaN,NaN,NaN,NaN
197,NaN,NaN,2,D,9,NaN,NaN,NaN,NaN,primer_box,NaN,NaN,NaN,NaN,NaN
198,NaN,NaN,2,E,1,NaN,NaN,NaN,NaN,primer_box,NaN,NaN,NaN,NaN,NaN
199,NaN,NaN,2,E,2,NaN,NaN,NaN,NaN,primer_box,NaN,NaN,NaN,NaN,NaN
200,NaN,NaN,2,E,3,NaN,NaN,NaN,NaN,primer_box,NaN,NaN,NaN,NaN,NaN
201,NaN,NaN,2,E,4,NaN,NaN,NaN,NaN,primer_box,NaN,NaN,NaN,NaN,NaN
202,NaN,NaN,2,E,5,NaN,NaN,NaN,NaN,primer_box,NaN,NaN,NaN,NaN,NaN
203,NaN,NaN,2,E,6,NaN,NaN,NaN,NaN,primer_box,NaN,NaN,NaN,NaN,NaN
204,NaN,NaN,2,E,7,NaN,NaN,NaN,NaN,primer_box,NaN,NaN,NaN,NaN,NaN
205,NaN,NaN,2,E,8,NaN,NaN,NaN,NaN,primer_box,NaN,NaN,NaN,NaN,NaN
206,NaN,NaN,2,E,9,NaN,NaN,NaN,NaN,primer_box,NaN,NaN,NaN,NaN,NaN
207,NaN,NaN,2,F,1,NaN,NaN,NaN,NaN,primer_box,NaN,NaN,NaN,NaN,NaN
208,NaN,NaN,2,F,2,NaN,NaN,NaN,NaN,primer_box,NaN,NaN,NaN,NaN,NaN
209,NaN,NaN,2,F,3,NaN,NaN,NaN,NaN,primer_box,NaN,NaN,NaN,NaN,NaN
210,NaN,NaN,2,F,4,NaN,NaN,NaN,NaN,primer_box,NaN,NaN,NaN,NaN,NaN
211,NaN,NaN,2,F,5,NaN,NaN,NaN,NaN,primer_box,NaN,NaN,NaN,NaN,NaN

In [264]:
update_database(primer_plates, 'primer_plates')
update_database(primer_box, 'primer_box')

In [271]:
XI_2_sq_fw = get_dna_from_box_name('XI_2_sq_fw', 'primer_box')
XI_2_sq_fw.annotations

{'box': 2,
 'row': 'B',
 'col': 1,
 'batches': [{'location': 'primer_box2B1',
   'volume': 'nan',
   'concentration': 'nan'}]}